### ISSUE TITLE
make sure user can not set dtend to something earlier than dtstart

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#11]

**Comment by georgehrke** [comment]
this should be implemented in the SimpleEvent object

**Comment by solarchemist** [comment]
I created such an event (by mistake) while using the "Create event" action from the Nextcloud Mail app (I had an email open in the Mail app, and clicked the dots menu, then "More actions", then "Create event").

The event had a prefilled start and end date which was the current date-time.
I changed the start date of the event to 2022-08-18 18:00, but due to unfortunate window size or something I then unintentionally clicked "Create" instead of changing the end date.

I wanted to make sure the event was created as expected (this was before I realised something was wrong), but the small popup that says "Event created" did not let me click on it to be taken to the event. So I opened the Calendar app and looked up the week of August 18, but there was nothing. So I used the search box, and there it was! But it showed start date 2022-08-18 and end date 2022-06-03, i.e., a physically nonsense entry.

I naturally clicked on the event in the search box, but that lead to nothing (completely white-out browser page, and any attempts to refresh resulted in nothing, ditto for going back - browser tab effectively dead).

So now I have an event that is is **not visible** in the Nextcloud Calendar, although it seems to exist (as evidenced by the search function), and no way to delete it. What now? :-)

PS. This might be a problem with the Mail app (I suppose its "Create event" should not allow the user to  create events with end date before the start date). But I'm also keen to clean up this freak event from my calendar, so any pointers very welcome. If necessary I can open a new issue (sorry for necromancing, and please advise!).

**Comment by solarchemist** [comment]
@ChristophWurst Done, please see https://github.com/nextcloud/mail/issues/6767 (I assume you meant for me to open the issue in the Mail app's repo).
