### ISSUE TITLE
Calendar 1.6.4 doesn't run on NC 15.0.2

### ISSUE THREAD

**Issue by navismo** [nextcloud/calendar#1102]
### Steps to reproduce
1. Update NC from 14 to 15 => Calendar is getting deactivated
2. Update Calendar to 1.6.4
3. Error message: Server version 14 or lower is required.

### Expected behaviour
Calendar should always update with NC

### Actual behaviour
See above and screenshot
![bildschirmfoto vom 2019-02-05 23-26-51](https://user-images.githubusercontent.com/47370785/52309244-d0bb8580-299f-11e9-88e5-eb0e03801fcf.png)

**Comment by georgehrke** [comment]
This is very weird, because the latest version is compatible with Nextcloud 15 and if you go to the apps store, download the release manually and look at the `appinfo/info.xml` it says:
```
<nextcloud min-version="14" max-version="15" />
```

Can you please try to click "Entfernen", make sure the folder "calendar" is gone in the "apps" folder and install again? 

It looks like the `appinfo/info.xml` was not properly replaced when you updated.

**Comment by navismo** [comment]
Yes, quite weird. Right now, some minutes later, i could activate the Calendar app. I didn't change anything, it just took some time to post this bug.
=> So right now it seems to work.

**Comment by tcitworld** [comment]
That's a server issue : since the front end is handled with VueJS, it doesn't reload the info.xml file after updating the app, hence the need to reload the page.

Will look tomorrow if the issue still exists or if there's an issue open.
