### ISSUE TITLE
Events with oc_calendarobjects.classification=1 not seen by sharing users

### ISSUE THREAD

**Issue by ThemGo** [nextcloud/calendar#1103]
For new created events, the value of column classification in table oc_calendarobjects is sometimes 0 and sometimes 1. This is no problem for the user who created the event, because he will see all the events regardless of the value of classification. But if it is a shared calendar, then it is a problem for the other users with whom the calendar is shared. Because they will see none of the events with 1 as value of column classification! 
It definitely is not an upgrading issue because both kinds of events where created after the last upgrade. 
Please fix.

**Comment by ThemGo** [comment]
Hmm, now I found https://github.com/nextcloud/calendar/issues/126
Does this mean that classification 0=public and 1=private?

**Comment by georgehrke** [comment]
These are the different classifications: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalDavBackend.php#L96

And this is the expected behaviour. It's controlled via the "When shared show ..." option when editing events.

**Comment by ThemGo** [comment]
Ok, I changed all classifications to 0 and now it works as I expected.
Say, is there any documentation of the database model?

**Comment by georgehrke** [comment]
> Ok, I changed all classifications to 0 and now it works as I expected.

Changing the classification in the database will not have a long-term effect, unless you change the `CLASS` inside the actual calendar-data.

> Say, is there any documentation of the database model?

Not really. We also don't encourage users to fiddle around with the database themselves, because you will most likely end up with inconsistencies like here, where the classification in the database does not fit the `CLASS` in the calendar-data anymore ...

**Comment by ThemGo** [comment]
I see. Thank you for the warning.  
Redundancy of data for performance I guess...

**Comment by georgehrke** [comment]
> Redundancy of data for better performance I guess...

Exactly. `calendar-data` is the raw calendar data provided by CalDAV clients. It is never touched or altered by the server in any way. It's the single source of truth.

The `classification` column in there to check whether an event is supposed to show up inside shared calendars without having to parse `calendar-data`, because that's a relatively expensive operation.
