### ISSUE TITLE
Duplicate event

### ISSUE THREAD

**Issue by renne** [nextcloud/calendar#113]
### Steps to reproduce
1. Click on a calender event
2. No "Store as new event" button
### Expected behaviour

In the event view/frame a button "Store new event" shall be shown besides/below the "Update" button which stores the edited event as a new one without changing the original one.
### Actual behaviour

Not available

**Comment by georgehrke** [comment]
Please explain a use-case

**Comment by renne** [comment]
1. User creates a complex event (title, date, time, location, description, multiple reminders, ...)
2. User needs same event with only a few changes (e.g. date and location)
3. User clicks on existing event
4. User edits the fields to be changed
5. User clicks "Duplicate/Save as new" button and event is stored with a new UID

The main reason for this use-case is to avoid re-doing the SAME complex settings in similar events which is also error-prone (typos, missing/mixing up locations, description, reminders, ...).

**Comment by georgehrke** [comment]
Do you agree?

**Comment by renne** [comment]
You mean a new event with copying attributes when typing a matching title? This would reference to #8 and avoids searching for the existing event.

I think that's a very interesting idea. Keep in mind not to reset the copied values when the title is changed! ;)

**Comment by scroom** [comment]
For our use case it would be good as well being able to duplicate an event or to copy it to another calendar. 
We've got a lot of calendars in use in our school in which some are publicized on the website, other are just intern, others are just shared with a certain group ....
It is really often necessary to have one event in several calendars so that all the people who have to know about the event, learn about it. It would save us hours if there would be such a functionality.

**Comment by Bugsbane** [comment]
I came here also looking for the ability to copy events, although my expectation for how it would be done was a bit different. I expected to be able to right click / long tap on an event and choose copy/paste, or if on a keyboard, to be able to drag an event to a new day while holding Ctrl / Alt / Option like in Dolphin on Linux / the File Explorers on Windows / Mac.

My use case is that I have a few work scheduled events that have the same title and time of day, but are on fairly random days. I'd really like to be able to take the one event I've already created for one of these and quickly duplicate it to other days (preferably without having to actually open the event).

**Comment by mrsynock** [comment]
holding ctrl while dragging to duplicate would be very good

**Comment by Bugsbane** [comment]
@georgehrke

> right click / long tap on an event and choose copy/paste

**Comment by georgehrke** [comment]
>  long tap on an event

Long tab on an event should be used to drag events to another time slot.

Let's do this with #17 instead. That will cover all use cases.

**Comment by JohnArcher** [comment]
I am in the same boat as @scroom and @dseomn ... That is the main thing that keeps me from using nextCloud calender instead of Google Calender. Copying/Cloning events to other calenders is very well done there.

**Comment by tikoflano** [comment]
Why was this feature request closed? I'm still needing this.

**Comment by JohnArcher** [comment]
@tikoflano I think this happend more or less accidentally when @georgehrke referenced #17 but this seems to be misleading, as we can't see what this issue has to do with cloning events. 
So I hope someone in the team can reopen it and give a statement where we are with this crucial feature.

**Comment by rkaraba** [comment]
Event cloning is would by a very usefull future. 
Sometimes is usefull to have the same event in different calendars shared with different people

**Comment by vince-from-nice** [comment]
I also need to duplicate or copy/paste events. 
Without that feature I am forced to stay under Google Calendar.
But if the issue remained closed there's no chance to see any evolution. Maybe we should open another issue ?

**Comment by georgehrke** [comment]
We discussed this at Nextcloud conf and came to the conclusion that #17 has a bad discoverability. 

We will include a Duplicate button in the new dropdown menu:
![5C1C647C-A0CA-4B70-9882-6C854D3E17E7](https://user-images.githubusercontent.com/1250540/64858921-08bb3300-d629-11e9-9b82-01bc8c44ad33.png)

**Comment by vince-from-nice** [comment]
Thanks for having reopened that issue, we really need it !

**Comment by memen45** [comment]
Missing this feature as well. I have a calendar created from subscription link. I do not need all the appointments from that calendar, so I want copy only the appointments I need to my personal calendar. An option "Copy to..." or "Duplicate" would be very nice! 

Currently I have to use the Google Calendar app to do this.

**Comment by georgehrke** [comment]
@memen45 Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting +1, 👍 etc. These kinds of comments just unnecessarily notify everyone subscribed to this issue. Thx! :)

**Comment by vince-from-nice** [comment]
I added +25$ via bountysource hoping that the issue will be promoted into an ealier version than 2.3 ;)

**Comment by vince-from-nice** [comment]
Apparently the issue title still need to be updaded manually.

**Comment by nsk7even** [comment]
> holding ctrl while dragging to duplicate would be very good
+1 for this, as it is really intuitive and fast

> @mrsynock how is that supposed to work on mobile? ;)
not - and this is ok, as long as it is an additional feature to enhance the desktop experience :)

**Comment by SLYtiger16** [comment]
Aside from adding the "button" and language to do this as shown:

> We discussed this at Nextcloud conf and came to the conclusion that #17 has a bad discoverability.
> 
> We will include a Duplicate button in the new dropdown menu:
> ![5C1C647C-A0CA-4B70-9882-6C854D3E17E7](https://user-images.githubusercontent.com/1250540/64858921-08bb3300-d629-11e9-9b82-01bc8c44ad33.png)

wouldn't this jus be as simple as calling the `createNewEvent` method in `/src/store/calendarObjects.js:315` and passing the _current_ event's object to it?
Nearly every calendar app available in nearly every other platform offers this functionality and this is a big reason for my company not moving away from google calendars. In fact I use the CalDav Android app **aCalendars+** to access my NC calendars whenever I need to clone an event and then let it sync back to NC because it offers this functionality. A pain to use a different product to get a clone on a NC calendar. Is there a chance to timeline this faster than December 2020 with 2.3? I would contribute but I am totally unfamiliar with Vue.js and it will take me quite awhile to figure out how to unravel the code...

**Comment by WNYmathGuy** [comment]
I would love this too. I've done two windows where I copy elements in one and past into a new event in another calendar. I've used the duplicate event option in the Android calendar app. I've exported events from Nextcloud and edited the file to reimport it. 

I really **hate** that we don't have a duplicate event yet. I'll get over that, but I would really love it if there was such an option.

**Comment by SilverPuppy** [comment]
I would like this too. I used to use Google Calendar for work at a previous employer, and we had this. It was very handy, because I wasn't forced to choose between re-entry or simply rescheduling a previous event, destroying the record that it happened. I won't say that I can't live without it, but this is an important feature.

**Comment by rogelio-o** [comment]
Any progress on this? I can see open PR #2400 from a couple of months ago, with the button but with empty click handling.

**Comment by canbuffi** [comment]
+1 This functionality is really important for our team too.

**Comment by cryptogoth** [comment]
+1 to merge this PR please (#2621 ), I'd like this feature to be able to move off of Google Calendar.
Thanks for your work @tcitworld @rogelio-o it looks like this is still blocked awaiting a code review.

**Comment by vince-from-nice** [comment]
Oh yes please review it, i have been waiting for it for so long and would be so happy to pay my $25 bounty.
@rogelio-o : Thank you very much for this PR. Hope it keeps the color attribute well when duplicating.

**Comment by SilverPuppy** [comment]
How do I add to that bounty? I REALLY am eager for this feature to be implemented.

**Comment by vince-from-nice** [comment]
You can add a bounty for this issue here: https://www.bountysource.com/issues/38109459-duplicate-event
I made mine almost a year ago...

**Comment by vince-from-nice** [comment]
@rogelio-o : Is your PR taking care of the color attribute when duplicating ?
@georgehrke (or another calendar dev): Could you take a look at that PR when you have time ? It's waiting for review for more than 6 months now.
Thanks a lot !

**Comment by SilverPuppy** [comment]
@vince-from-nice Thanks for the tip. Before I throw them some of my hard-earned money, wasn't this the outfit that changed their TOS to say that after a year or something like that they get to keep the money if the issue is never resolved? I think they changed the TOS back after a FUROR erupted online over it, but that was a trust issue. Was that them?

**Comment by vince-from-nice** [comment]
@SilverPuppy I admit that I don't really know these stories but what is certain is that the 25 € of my bounty was indeed withdrawn from my account in April 2020 while the functionality has not been developed.

**Comment by SilverPuppy** [comment]
Gitcoin.co looks legitimate, and seems to have a good reputation. Would a bounty posted there do any good? Would anyone see it? (Of course, now it's been mentioned here LOL)

**Comment by cryptogoth** [comment]
I second Gitcoin and have used it successfully. I'd be willing to help 
fund / project manage this as well, but are the Nextcloud org willing to 
merge the PR and integrate it into a future release?

Is it simply lack of funding and resources to do it?

**Comment by rogelio-o** [comment]
Thank everyone! The PR is waiting for review yet.

@vince-from-nice, the PR takes care of the color when duplicating as you can see [in this line of code](https://github.com/nextcloud/calendar/pull/2621/commits/65deb046575b9f4c868fe836545bc50db2c4f03b#diff-118fda3f1298728b6e2fdeb882c3a47a4686639d2c45a7c003f4f622748d3399R223).

**Comment by alexanderdd** [comment]
Related: https://github.com/nextcloud/calendar/issues/2659

I think that in a lot of cases, it would be better to invite yourself to an event from a shared calendar (then it will show up in your personal calendar) instead of duplicating the event from a shared calendar to your personal calendar. Duplication will not inherit changes, invitiation will inherit changes.

**Comment by alexanderdd** [comment]
Can someone please reply and explain why **duplication** is more important/more useful/higher priority than **inviting yourself**?

> Related: #2659
> 
> I think that in a lot of cases, it would be better to invite yourself to an event from a shared calendar (then it will show up in your personal calendar) instead of duplicating the event from a shared calendar to your personal calendar. Duplication will not inherit changes, invitiation will inherit changes.

**Comment by WNYmathGuy** [comment]
> Can someone please reply and explain why **duplication** is more important/more useful/higher priority than **inviting yourself**?
> 
> > Related: #2659
> > I think that in a lot of cases, it would be better to invite yourself to an event from a shared calendar (then it will show up in your personal calendar) instead of duplicating the event from a shared calendar to your personal calendar. Duplication will not inherit changes, invitiation will inherit changes.

It could be just for myopic reasons, but I found it very useful when I used to googleify all my info before Nextcloud. For example, some events, like a medical appointment, have the property of being rescheduled the same day as the current appointment is being finisher; dental cleanings, annual physical exams, medication for pets. With a "Duplicate Event" button, I could open the event that just happened with all the pertinent information like location and reminders, and create a new one only needing to edit the date they are scheduling the next appointment. Also, there are ad-hoc events that don't have a routine schedule of repeats but have a lot of common elements. If I have four sessions to meet with some people for group work, I can make four copies of the first one and move their dates and locations leaving all other event details the same.

"Duplicate Event" is very handy for people who are not all using the same system where inviting oneself is not a good option due to some attendees not having a share of the system. 

Some things to put on a calendar like Easter, or similarly Mardi-Gras would be ideal for duplication because setting a repeating pattern is futile.

**Comment by nsk7even** [comment]
> Can someone please reply and explain why **duplication** is more important/more useful/higher priority than **inviting yourself**?
> 

For me this is a different use case.

I would need the "duplicate event" feature to create a new event on a different time, but with same title and mostly same description - which I would edit/update afterwards.

This is not a very common use case, I have to admit. A concrete example is a todo list that is scheduled to a specific date and that should be copied to another date as a template.

**Comment by SilverPuppy** [comment]
I am in the service industry, and when I had the option to do it in the sCroogle days, I would use the duplicate function (with a little editing) to create go-back appointments without having to re-enter the customer's information or lose the record of the first appointment. In some industries, the duplicate event function is highly useful.

**Comment by SilverPuppy** [comment]
"Duplication will not inherit changes, invitiation will inherit changes."

Therein is the entire point when you're in the service industry. In my use case, I don't want the changes to duplicate. Also, the goal for me was never to duplicate across calendars, but to different dates within the same calendar, for reasons I have explained previously.

**Comment by khampf** [comment]
Entering weekly schedules without the option to use a previous entry as a template is a pain in the behind. I now use calendar 3.0.2 but this functionality was recently added to milestone v2.4.1?

**Comment by tcitworld** [comment]
We're going to clean-up the milestones tomorrow, they don't mean much right now.

**Comment by KrLx1994roller** [comment]
Any update on this? :)

**Comment by ASLLR** [comment]
Hi, did we have an anoucement of release of this option ?

Thank in advance,

**Comment by ChristophWurst** [comment]
No

**Comment by ASLLR** [comment]
> No

Thank you for your reply.
We want to use this plugin in our company which has several thousand users and I am convinced that nextcloud would meet all our needs but I would need arguments to counter the GAFAM... This option is very useful for many users, and this failure could tip the final choice. It's a shame not to dwell on it... 

Have a nice day,

**Comment by bovender** [comment]
I often have to create multiple very similar events within one calendar, and it is cumbersome when using the Nextcloud web app having to re-enter all the details when only few details change.

Is copying and editing the duplicated event really such an esoteric use case?

In fact, when I have to create multiple events, I often pick up my CalDAV-enabled smart phone which offers that feature -- or my laptop (running KDE neon) whose calendar application offers the functionality too. But there are many times when all I have is a web browser on some PC at work, and then I find myself wishing for this functionality in Nextcloud proper as well.

**Comment by ant0nwax** [comment]
Hi folks, I just came to the point where I needed to duplicate a recurring calendar event and i see that this SIMPLE!!!! feature that was reported 2016 and 2019 it was decided to integrate it to the new dropdown menu, is still not finished. I agree that you do a good job with the nextcloud and most likely mail and calendar is NOT of your scope at all, those are plugins and apps running  in the nextcloud, but it is hardly usable for replacing another calendar, so why did you develop calendar at all? the mail app i already uninstalled, I would wait 1 year from now and see if the duplicate event action is available, if not i will also uninstall the calendar, because this is how you solve to get less clients... Thank you for reading

**Comment by zgjavi** [comment]
This functionality is quite necessary.

**Comment by x12a1f** [comment]
I have another use case for this feature.

I would like to use the calendar to schedule the day for my children. Events and/or tasks wil be something like 

* 7:45 - wake-up, get dressed
* 8:00 - breakfast
* 8:15 - gather school supplies
* 8:20 - gaming until school bus arrives
* 8:30 - go to school
* etc...

Most days are the same, however there are to many day-to-day changes to use the repeating event feature. It would be nice if I can just shift+drag an event and/or task in the calendar from a previous day to duplicate it to a new day.

There are apps which can do this, but they require a monthly fee. Mostly they are for children with autism and although they offer more features, from what I have seen from it, they are just a simple shared calendar with some magic around it to make creating schedules easier. I figured I can do this with nextcloud also, but having a easy way to duplicate events would be really helpful.

**Comment by fhaut** [comment]
This feature request are important and usefull
another missing simple feature is a field URL that opens the link on new tab. 

only these two requests to leave google calendar in the organization...

**Comment by ant0nwax** [comment]
I agree that for Business usage the Duplicate event feature ia a K.O. criteria

**Comment by eule68** [comment]
I wonder what is so complcated in adding this feature, that the discussion takes years. This feature is very important and a IMHO a basic feature for every calendar. I can't believe that it seems to have such a low priority. This is also important for copying an appointment to multiple calendars (participants), as the function to add people to an appointment does not cause it to appear in their calendars as well.

**Comment by ant0nwax** [comment]
As I work now for 6 month inside a company that creates another open source solution I am aware that the developers would really like to solve this, but there must be more relevant issues to more people, that's why this thread has not enough focus. Everyone that writes here and IS able to develop (sorry, i am not) could help to get this feature forward as nextcloud calendar plugin is open source, too.

**Comment by szaimen** [comment]
Hello everyone 👋

Today is your lucky day because I took the time and implemented this feature based on the work of @rogelio-o which implemented most of the desired feature in #2621.

See https://github.com/nextcloud/calendar/pull/4300 for my PR.

If you have docker locally installed, you can test this with:
```
docker run -it \
-e CALENDAR_BRANCH=enh/113/duplicate-event \
-p 127.0.0.1:8443:443 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

**Comment by SilverPuppy** [comment]
@szaimen MY HERO! I can't test easily this just this moment as my setup is not Docker based, but can hardly wait for it to appear through automatic update of the Calendar app. When might this happen? I realize this depends on people other than yourself, of course; it's just a question about the general development cycle, I suppose.

**Comment by eule68** [comment]
Hip-hip hooray.

Many thanks and a big beer.....

**Comment by SilverPuppy** [comment]
My looking at things indicates that the next release of this app should include this. If so, YAY! If not, tell me where my understanding took a wrong turn. :)

**Comment by ant0nwax** [comment]
I just updated to 3.4.0 and its not in the changelog and not in the three dot menu, please define 'next release of this app with a version number', thanks

**Comment by st3iny** [comment]
It will most likely be included in V3.5.0.

**Comment by eule68** [comment]
I was expecting 3.5.0 to be the next version and to be released shortly, but in the meantime there are two intermediate versions.
Why isn't this important patch not included in these releases ????

**Comment by fhaut** [comment]
im dont understant too, switching back to google calendar.. by by nextcloud.

**Comment by SilverPuppy** [comment]
My machine updated itself to 3.5, and I can confirm this feature finally works as expected. Huge thanks to all the people who finally made this work!

**Comment by SilverPuppy** [comment]
> im dont understant too, switching back to google calendar.. by by nextcloud.

3.5 is released, and this feature works as expected.

**Comment by krauthosting** [comment]
Thanks :partying_face: Just confirmed via Snap auto update works:
![image](https://user-images.githubusercontent.com/69597449/189339927-f9bebd07-ecf6-4508-afbc-7f381c970098.png)
Didn't work in quick testing for ended recurring series.

**Comment by fb95** [comment]
Is it possible to have the same duplicate menu entry for imported agenda (by URL) ?

**Comment by alexanderdd** [comment]
@krauthosting and @fb95 please open new issues.

@fb95 as a workaround, you can always export a whole calendar to .ics and then import that calendar into any calender on your Nextcloud instance. If you need more support, please use help.nextcloud.com

**Comment by gitwittidbit** [comment]
Um, I'm on the latest NC with the latest version of the Calendar app. But I don't have (or am not able to find) the "Duplicate" button.

Has it been removed again? Is this not in the NC Online Calendar but some other app? If so, is there a way to duplicate a calendar entry in the NC online Calendar app?

Thanks.
