### ISSUE TITLE
Issue with Calender reminder on Mobile Apps

### ISSUE THREAD

**Issue by Mululu** [nextcloud/calendar#1278]
Actual behaviour
The following scenario:
User 1 creates a calendar and shares it with user 2. There are several appointments in this calendar. Each appointment has a reminder 1 day before.

User 1 has an Android phone and uses the Davx5 app and it will display 1 day's reminder

User 2 also uses an Android phone with the Davx5 app. It will not show any reminders.

In the web browser, are the same problem

Either the calendar is not fully shared with reminders, or the Davx5 app can not read anything or is not assigned by nextcloud.

If I give the user 2 a write permission to test and only open the appointment and update without changing anything, the 1-day reminder will also be displayed on the Android user 2.

Enclosed screenshots from Google Calendar once from user 1 and user 2. Both have the same calendar from nextcloud.

With Apple the same problem could be determined

_I know this is intentional but it is not a good solution. You should leave an option open to decide for yourself.

In addition, one could synchronize the syncronization using the DavX5 developers so that there is a possibility in the app ._

**Comment by georgehrke** [comment]
> If I give the user 2 a write permission to test and only open the appointment and update without changing anything, the 1-day reminder will also be displayed on the Android user 2.

This is done on purpose, because users can't disable alarms for read-only calendars since they are not allowed to modify the event.

Even worse, most clients will store the information, that a user acknowledged an alarm, inside the calendar data. But since the user is not allowed to edit the event, some clients will just keep spamming the user with an alarm till eternity.

**Comment by Mululu** [comment]
A solution is needed. And do not just avoid a problem.

**Comment by georgehrke** [comment]
We are planning on fully implementing https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-sharing.txt, but i can't give you a roadmap for that yet.

https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-sharing.txt#L791 states, that among other things, alarms have to be treated as a user-specific option, so that each user can define their own alarms.

**Comment by Mululu** [comment]
How about this?  If a calendar with a reminder is shared as read only, the reminders are still not shown to users.  Where's the switch for this selection?

**Comment by ronau** [comment]
Do I understand correctly, that if the calendar will be shared with edit permission, then the shared user will see the event alarms on his/her devices?
Also, will dismissing an alarm somehow involve syncing activity with regard to the affected event? I mean, if the shared user dismisses the alarm, will this affect what is going on on my devices?

Sorry for digging up old issues.

**Comment by georgehrke** [comment]
> Do I understand correctly, that if the calendar will be shared with edit permission, then the shared user will see the event alarms on his/her devices?

Yes

> I mean, if the shared user dismisses the alarm, will this affect what is going on on my devices?

That depends on the client, but it might.

**Comment by Mululu** [comment]
Hello,

it would be really great if you could set whether users without calendar permissions should receive reminders or not.

We share our fire brigade calendar via Nextcloud and everyone should get a reminder 1 day before the fire service. However, I would have to give everyone or the group write access to the calendar. But that does not make sense.

Can you add this feature please?

Or is there a possibility to change this by means of some coding?

Thank you!
