### ISSUE TITLE
UNDO event deletion

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#13]

**Comment by georgehrke** [comment]
My current approach is a yellow notification at the top.
This notification will disappear after n seconds.
If the user clicks the notification, the deletion will be undone.

@nextcloud/designers What's a reasonable after which the notification can disappear?

**Comment by eppfel** [comment]
This touches on the bigger issue of notifications in general. see nextcloud/server#301

**Comment by jancborchardt** [comment]
@georgehrke the general agreed upon time is 7 seconds. 5 is just a bit too short to notice, and 10 is too long.

And yeah, just to clarify: We talked about this if we want to use an undo notification in the place where it happens or on top. Right now it seems a notification up top is better since then it’s out of the way and seems quicker. We can directly fade out / animate away the element. @georgehrke the animation part is important for visual feedback, check how we do it in the Mail app with slideUp. :)

**Comment by patrice-geo** [comment]
Even with the undo function, there should have a confirm prompt in the first place, as explained in #573

**Comment by jancborchardt** [comment]
@patrice-geo no, both confirmation and undo do not make sense. You can read about why confirm prompts are a bad idea at https://alistapart.com/article/neveruseawarning

**Comment by tcitworld** [comment]
Is this still worth it with the trashbin?
