### ISSUE TITLE
Conformation message for deleting calendar only in English

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/calendar#1489]
I think the message comes from this file:
js/app/directives/confirmationDirective.js
And my guess is the string from the message isn't language aware yet.

### Steps to reproduce
1. Delete a calendar
2. Wait for conformation message and countdown

### Expected behaviour
Message should appear in UI langage

### Actual behaviour
Message appears in English

### Server configuration

**Server version:**
15.0.10

**Calendar version:** (see the apps page)
1.6.6

**Comment by tcitworld** [comment]
Please update to the latest version of the Nextcloud server and calendar app. 15 is pretty close to end of life and only gets security fixes.

**Comment by mjanssens** [comment]
@tcitworld 
A bit strange that the bug is closed while 15 is still inside support (although not for long I know).
Holding me back form upgrading to NC16 was the upgrade from Debian 9 to 10, so PHP 7.0 to 7.3.
In the meantime I upgraded to Debian 10 and after that NC16.
So now I tested the issue with:
Nextcloud 16.0.4
Calendar 1.7.1
Result: Message appears in English

**Comment by raimund-schluessler** [comment]
The problem is that this string https://github.com/nextcloud/calendar/blob/master/js/app/directives/confirmationDirective.js#L48 is not translated. Simply wrapping it in the `t(...)` function would solve it. But I don't know if it is worth it, because this file will be obsolete with the Vue rewrite.

@georgehrke @tcitworld In case there will be a version 1.7.2 of Calendar, I can send a PR.

**Comment by rkaraba** [comment]
When do you plan to lunch Vue version?

**Comment by georgehrke** [comment]
This was fixed in version 2 and is no longer reproducible:
https://github.com/nextcloud/calendar/blob/fe9a0e1c3edba226ad578f1d13fc88d16671683c/src/components/AppNavigation/CalendarList/CalendarListItem.vue#L113
https://github.com/nextcloud/calendar/blob/fe9a0e1c3edba226ad578f1d13fc88d16671683c/src/components/AppNavigation/CalendarList/CalendarListItem.vue#L119

Version 1 is only receiving security updates, so a backport is not planned

**Comment by mjanssens** [comment]
@georgehrke sorry for not updating my comment. NC 15 is end of life, so it doesn't apply anymore.
In the meantime I'm on NC 17.0.2.1 and Calendar 2.0.1 and the issue is indeed not reproducible.
Thanks for fixing!
