### ISSUE TITLE
The new created calendars are not activated by default

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1588]
Do we need to set `calendar-enabled` on calendar app side or is this an issue on server side?

**Comment by georgehrke** [comment]
It's both kind of. 

There is no default visibility in the calendar app, so if none is set, it's just hidden.
But it's also a server-side issue, since we set calendar-enabled in the MKCOL request.
But the server doesn't save properties that are not stored inside oc_calendars on MKCOL.

But for calendars that you own yourself, if there is no visibility set, the default one should be enabled.
