### ISSUE TITLE
Event details are not transfered when switching from simplified editor to sidebar

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1590]
Applicable for title, start & end date,…

**Comment by georgehrke** [comment]
Okay, so identified multiple problems here:
Edit existing event:
- Event title and other information are transferred just fine.
- non-recurring: Changing the starting time does not work, because that changes the recurrence-id and hence opening the sidebar will fail, because it can't find the event
- recurring: all information is lost, because recurrence-instance does 

New event:
- all information is lost, because it generates a new calendar object instance.

Proposed solution: just store calendarObjectInstance in vuex.
@tcitworld Any objections?

**Comment by tcitworld** [comment]
> Proposed solution: just store calendarObjectInstance in vuex.

Yeah, it's the easiest solution.
