### ISSUE TITLE
Add feature to invite groups

### ISSUE THREAD

**Issue by christoph-puppe** [nextcloud/calendar#163]
Hi

Would be nice to invite groups to an event.

All members of he group should get a notification. 

All members should be able to accept/decline/maybe 

The event should show a listing of who is attending. 

Comments would be cool too  

Thanks in advance

**Comment by georgehrke** [comment]
@christoph-puppe Groups from the contacts app or groups of Nextcloud users?

**Comment by christoph-puppe** [comment]
@georgehrke Groups of nextcloud users. We're using a custom oAuth2 plugin to import groups from an external IDp and would love to use this groups for events with invites, not only shared calendars.

**Comment by georgehrke** [comment]
Hm, that's very problematic.
We need the e-mail address of users to invite them.
First of all it's possible that not all users provided an e-mail address earlier and we would also disclose other user's e-mail addresses. I'd actually consider such a disclosure of user information a security issue.

@LukasReschke Do you have an opinion?

**Comment by christoph-puppe** [comment]
In my case all users have an email-address, disclosure would only happen if the listing of participants would show their address, which is not needed.

**Comment by georgehrke** [comment]
> disclosure would only happen if the listing of participants would show their address, which is not needed.

It is needed for sending out the invitations and thus the e-mail-addresses would also appear in the ics file.

**Comment by christoph-puppe** [comment]
leave it to the admin to decide if group-invites are wanted, even if the group does see the addresses then? Many environments the emails are known to all anyway.

**Comment by copeceeso** [comment]
Has this enhencement been validated?
Would it be possible to add nextcloud group so all users in the group would be attendees (even users without email)?

**Comment by georgehrke** [comment]
Closing in favour of #167

**Comment by kainhofer** [comment]
@georgehrke I don't think that #167 is a duplicate of this issue. This issue is about invitint all members of a Nextcloud group, while #167 is about inviting contact groups, which exist solely in the addressbook.

I'm in the same situation as the OP: I'm managing a large organisation ~500 members with several formal working groups. Each working group has memberships, which are modelled with Nextcloud groups (to provide shared folders for the work in the group). The memberships are handled centrally by the secretary. For WG meetings, we'd like the WG chair to simply invite the Working group and let nextcloud handle the invitation handling. 
True, the chair has the emails of all participants in the ics file, but the attendees do not (provided nextcloud properly implements the standard). 

There are not contact groups to be used (actually, we do not provide the contacts app in the first place).

**Comment by JLueke** [comment]
Inviting users individually could be the base to invite a group (group invite = multiple user invites). I think for a first step it would be enough, to send the invitation via E-Mail.

**Comment by JLueke** [comment]
As a user I would think the search is broken if the user suddenly doesn't appear. I suggest that, if a user has no E-Mail, then the user search suggestion could be marked with e.g. a crossed-out email Icon and/or show an error message if the event organiser tries to invite the user anyway. Or maybe always show an email icon with green as "is set" and red as "not set".

**Comment by blue995** [comment]
@georgehrke I also think that this is not a duplicate of #167.

This feature would be convenient to invite e.g. ~60 users (all part of the same user group) to an event.
I don't know how to achieve this currently (2.0.3) without selecting them one by one. Maybe I'm missing something.

**Comment by sujaysreedhar** [comment]
+1

**Comment by julian70400** [comment]
So, what's up ? 
This feature is really important for most of us which have large communauty. Actually, I can't use agenda to organise large event. It's sad. 

Will this feature being a day added ?

**Comment by flowmans** [comment]
Hi,
Not being able to invite attendees at once already setup as a group in a contact list for any occasion makes the whole nextcloud platform obsolet. Nobody is interested to spend endless time to add participants one by one to an invite. 
Is there any chance to get this fixed soon? Otherwise we will use another sharing platform. It really costs more time than it helps right now.
Tom

**Comment by jpubb** [comment]
I don't understand why this is closed. Can't imagine MS Exchange environements without the ability to message groups composed of company  users (Distribution Lists)

**Comment by erzwo31** [comment]
+1 from me

In my case, I'd want to invite 100+ Nextcloud users (all of the same Nextcloud group) to calendar events (which happen offline). Our users are all registered with an email address. The invite attendees should allow (at least for the group admin) to invite the whole group, which then triggers the sending of individual invitation emails to the group its users. As simple as that. Each user gets an individual email, without leaking the other emails.
