### ISSUE TITLE
Setting Page

### ISSUE THREAD

**Issue by CoolJoni** [nextcloud/calendar#1715]
Currently there is only a settings popup available. In order to be able to set holidays and public holidays later, a separate settings page would make sense. 
Also further settings like standard colors or other would be easier.

**Comment by georgehrke** [comment]
Not sure this is a valid enhancement request? 

As long as all the settings we have fit into the lower left box, it's gonna stay like that, because that' the standard design for Nextcloud. Once we offer more or only advanced settings, we can talk about a dialog or dedicated settings page.

But we won't add more settings for the sake of adding settings. We are pursuing good defaults and only provide settings where it makes sense.
