### ISSUE TITLE
Sticky save buttons

### ISSUE THREAD

**Issue by Helium314** [nextcloud/calendar#1960]
When entering a long event description (many lines) I notice two inconveniences.

1)
The save/update button gets moved down, so with long descriptions I have to scroll down to actually click it.
Would is be good to have it always visible? I fear that would require quite a bit of work for only a minor change, but for me it would still be good to have.
Same goes for the close button, which is always in the top line; with long event descriptions it can be scrolled out of view.

2)
The description field seems to have a maximum size, and I have to scroll within the field. But this only works when using the arrow keys, not when selecting text and there is no scroll bar.
Scrolling when selecting text that is not visible any more and a scroll bar would be nice additions, and I would expect both of them when comparing with similar fields (like here on GitHub in the field where I'm writing this text).

Calendar 2.0.1, Nextcloud 17.0.2
Edit: Browsers used: Edge and Vivaldi

**Comment by codeling** [comment]
I can only second that, in my opinion this is really bad usability regarding this specific aspect. The update button is only visible after scrolling down on 1920x1080, which is probably the most commonly used resolution at the moment. Other apps on nextcloud (e.g. Contacts) actually don't have an update button (anymore?), so the user could be lead into thinking this is the case also here. But when she/he just closes the issue, any changes made in the meantime are just lost!

The update button needs to be at least as visible as the close button, and these two need be close to each other so that users can easily deduce the usage pattern expected from them.

**Comment by alexanderdd** [comment]
@Helium314 can we split this in two? I suggest to rename this issue to "update button in sidebar hard to find"
and move "2." from your first post to a new issue called "scrolling in long description in sidebar"

About 1.: I think the update button should always be visible at the bottom of the screen, and content should flow behind it. This will also be good for smartphones.

Mock-up:
![Bildschirmfoto vom 2020-03-15 02-29-11](https://user-images.githubusercontent.com/28591861/76693446-5ad72280-6665-11ea-9d61-8fb156ef9868.png)

**Comment by RobertZenz** [comment]
Regarding scrolling, the *initial* size of the description is two lines when opening an event. After a layout-pass (for example a window resize) the description fields gets resized to the full length of the description.

**Comment by alexanderdd** [comment]
@georgehrke @Helium314 @RobertZenz 
What do you think about: Update button should always be visible at the bottom of the screen, and content should flow behind it. (Mockup above) ?

Should I open a separate issue for it (it is not only about a long event.description). I think it is really bad UX at the moment, not autosaving and also hiding the save button out of the screen.

**Comment by RobertZenz** [comment]
Most likely a simple and good way, yes. I'd still consider to have a minimum and maximum size on the textfield.

**Comment by georgehrke** [comment]
A pull-request would be much appreciated ;)

**Comment by alexanderdd** [comment]
@georgehrke can you put this on 2.2.0 milestone?

I believe this is really important for usability. New users might enter data and not see the "save/update" button because it is off-screen, click somewhere else, and be irritated why this was not saved. The save/update button needs to be **always** visible, see my mockup above. Or move save/update button to the top of the sidebar, or we do autosave always.

**Comment by alexanderdd** [comment]
@RobertZenz @codeling @Helium314 can you contribute to this in any way? Do you know someone who can, or do you have other ideas how to make this happen? I have tried hiring someone for specific bugs on fiverr and upwork, but only had bad experienes so far... I still think this is a major usability issue and would be ready to put money on it (not a lot though). Bountysource must not be used anymore, so I am not sure what to do.

**Comment by codeling** [comment]
@alexanderdd sorry but no, no time at the moment!

**Comment by Helium314** [comment]
Sorry, I probably can't help at all with such things, as I am not really experienced in coding (if anything, then I'm using matlab or trying to fix small things in android apps).
I can still try playing around if you can point me to the right location...
