### ISSUE TITLE
Visibility of shared calendars

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2090]
**Is your feature request related to a problem? Please describe.**
Create a shared calendar.
For users that you shared it with, the calendar is hidden by default, they have to actively enable the calendar in the sidebar to see it.
**Describe the solution you'd like**
When a new calendar is shared with you, it is shown. Of course you can hide it.

**Additional context**
Nextcloud claims to have **sensible defaults**. The current situation is not a sensible default because inexperienced users will not see the calendar and think it is not there.
Currently, I (admin) have to explain to all coworkers how to show the shared calendar, or do it by hand for everyone via impersonate.

**Comment by georgehrke** [comment]
I still believe that our current behavior is a sensible default. Especially now, when everyone goes into home-office and starts sharing their calendars with everyone else, I do not want my calendar view to be flooded by the calendars of dozens of coworkers. I want to see my normal calendar view and pick a coworker's calendar when i want to see it.

I find a scenario, where you open your calendar app and you suddenly see not only your events, but also the events from calendars of dozens of coworkers, very confusing.

---

To come back to the problem you described: The problem doesn't seem to be that the calendars are not visible by default, but that users never get a notification or any other kind of hint, that someone shared a calendar. 
So as an alternative proposal: If user a shares a calendar with user b, user b should receive a notification. When clicking on that notification, it should open the calendar app and mark that calendar as visible.

cc @nextcloud/designers

**Comment by georgehrke** [comment]
@alexanderdd If you want to patch the current behaviour, just change https://github.com/nextcloud/calendar/blob/master/src/models/calendar.js#L127 and rebuild the calendar app as described in the Readme file.

**Comment by tcitworld** [comment]
> So as an alternative proposal: If user a shares a calendar with user b, user b should receive a notification. When clicking on that notification, it should open the calendar app and mark that calendar as visible. (or only show the shared calendar)

Related to https://github.com/nextcloud/server/issues/19568

**Comment by georgehrke** [comment]
> Related to nextcloud/server#19568

I would close this in favour of nextcloud/server#19568 in that case.

@tcitworld Any objections?

**Comment by tcitworld** [comment]
Yeah but don't forget to edit the description to reflect that, as it's not exactly the same thing I wrote in that issue.

**Comment by georgehrke** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/19568#issuecomment-603169172

**Comment by jancborchardt** [comment]
Your proposal with the notifications sounds good @georgehrke, and closing in favor of that issue too :+1:

**Comment by alexanderdd** [comment]
@jancborchardt @georgehrke @tcitworld 
I disagree. Shared calendars should be visible right after sharing.
* calender sharing should work the same way as folder sharing. When I share a folder, it is automatically shown for other users, right? At least for group shares, which I use.
* I assume that most users do not have 50 coworkers that share their personal calendars. (it would be good to have some real data here?) I assume the most widespread situation is personal calendars plus 0-4 shared calandars. If this is true, sensible defaults should reflect this. 
* if I share something with a person/group it means I want them to see it. (we should not assume I do it just to annoy them)
* a lot of users never look at/interact with notifications
* automatic showing of shared calendars means less support requests from people who "don't see the group calendar"

You can of.course do what you like. I just wanted to share my thoughts because I am also interested in a better product.

**Comment by georgehrke** [comment]
> calender sharing should work the same way as folder sharing. When I share a folder, it is automatically shown for other users, right? At least for group shares, which I use.

I strongly disagree with the comparison of Files and Calendar here.
If you share a folder with another user, it will pop up in their Files app and they have to click it to view its content.
This is the same behaviour with the disabled-by-default calendars. The calendar-name will popup in the left sidebar and users will have to click it to see the actual events.

> I assume that most users do not have 50 coworkers that share their personal calendars. (it would be good to have some real data here?) I assume the most widespread situation is personal calendars plus 0-4 shared calandars. If this is true, sensible defaults should reflect this.

Since Nextcloud does not track users, we do not have any data about this. But there are many many instances out there with tens of thousands and more users. From personal experience and also the bug reports / feature requests we have received so far, having dozens of shared calendars seems to be far more common than you might think.

> if I share something with a person/group it means I want them to see it. (we should not assume I do it just to annoy them)

No doubt about that. But if we display shared calendars by default, it's very intrusive. Instead of giving the user to option to look at your calendar when they want to, you force them to take action immediately when they open the calendar app. 

> a lot of users never look at/interact with notifications

Again, we do not have any data about this. This seems to be your experience from administering a Nextcloud instance, but judging from the feature and bug reports we receive, i can say that people are using notifications. If they didn't, it wouldn't be a reason to completely abolish notifications, but to improve discoverability.

**Comment by diemelone** [comment]
Maybe you haven't got data for that, but given that people still search for that same exact problem hints a quite strong desire, doesn't it? 
The world isn't black or white, so why not compromise on a option to select in the settings section, that way any user can change the default previously set by the admin.
At least for me this would totally make sense, I use NC for my family and a scouting group, both of which groups I would consider consists mainly of users without much intuition and motivation to learn yet another system. For users like them such an option is crucial. Even handling the calendar right  and not accidentally hiding it is a major problem for some of them.

> @alexanderdd If you want to patch the current behaviour, just change https://github.com/nextcloud/calendar/blob/master/src/models/calendar.js#L127 and rebuild the calendar app as described in the Readme file.

If you wont implement this feature would you please provide a instruction on how to do it without much programming experience?

**Comment by ryan77627** [comment]
I'm going to chime in my use case for data purposes :)

I would like to have the shared calendars show up by default because we all have shared calendars, and various people involved with a certain project (we are using this for film production) get the shared calendar. Not having it show up by default adds at least an extra step for users to see when they're expected to show up for filming, at worst a message to me. I have rebuilt the calendar app a month and a half ago, but I don't really have the time to maintain it to the degree I would need to. When I upgrade, the changes go away. It would be nice to have a config option for this to make it more permanent.

**Comment by alexanderdd** [comment]
> Since Nextcloud does not track users, we do not have any data about this. But there are many many instances out there with tens of thousands and more users. From personal experience and also the bug reports / feature requests we have received so far, having dozens of shared calendars seems to be far more common than you might think.

Ok, I agree that we do not want users to open calendar app and see chaos because 20 shared calendars are visible.

@georgehrke In the spirit of sensible defaults, what about this:
**If there are <5 calendars shared with a user, and a new calendar gets shared, make it visible.** If there are >5 calendars shared with a user, do not make newly shared calendars visible.


----------- going off-topic ---------------------
Another idea would be: if a new calendar gets shared with a user, show a popup right next to the button the user has to click to activate it (thereby teaching or reminding the user how to show/hide calendars). But that would introduce a whole new way of interaction, that discussion exceeds this topic here.

> And even if they didn't, it wouldn't be a reason to completely abolish notifications, but to improve discoverability.

For example make a difference between "regular" and "important" notifications, show imporant at the top, highlighted.
