### ISSUE TITLE
Remove valarms from objects in read-only shared calendars

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/calendar#211]
From server repo, as it fits here better ;-)
https://github.com/nextcloud/server/issues/679

In ownCloud once there was a patch that removed valarms on shared calenders.
The purpose is to not be flooded by alarms by read-only shared calenders.

Ref: owncloud/core#24377

**Comment by tobiasKaminsky** [comment]
@nursoda

My family and my colleague use NC and have their own calendars. They shared some of them read-only and some of them read-write. They set up alarm, all of them ring on my phone, but I don't want to see/hear all their reminders!

I write this since I think that the proposed "solution" doesn't eliminate the root issue. Why?

I'm a secretary. I manage appointments for my boss. I see 3 possible user expectations:

    I also set up reminders for him (only), since that's what he expects me to do: manage all his calendar.
    I might set up alarms in his calendar that are meant to me (like to prepare the room). One might argue, that in that case I should add an event with alarm in my own calender. OK, I can live with that.
    Only my boss may set up reminders on his events (since it's his phone ringing then, after all).

So, I vote alarms be INDEPENDENT of the calendar status (read-only vs. read-write). Proper solutions could be to add a property that lets a user select

    whether or not to share valarms (read-write/read-only same as calendar itself) -or-
    whether or not to import valarms - or-
    for which user(s) an alarms should ring.

**Comment by georgehrke** [comment]
Server repo was correct

**Comment by aslmx** [comment]
Hope it is fine to reply to a closed issue...

Interesting. So it's not a bug it's a feature ;-)

I handcrafted a long list of VALARMS manually into some ICS File because the local waste disposal provider does not include them any longer in their iCalendar download. Long story short. I Imported the handcrafted ICS file. All reminder show up perfectly. Now I wanted to share this reminders with my wife, so either of us can take care of putting the waste bins to the street to be picked up. 
I thought I found a bug when Reminders were not shown in the read only view on my wife's NC account side. 

Workaround was to just import the hand crafted ICS as another calendar into her NC calendar. But this is extra work and against my expectation.

**Any recent discussion if sharing Reminders can be made optional?**

 I understand the arguments listed above, but I think there are valid use cases of sharing reminders.

**Comment by georgehrke** [comment]
There are more issues with reminders in a read-only calendar, which have not been discussed here yet. One of the biggest is an issue with Thunderbird, which stores whether or not a reminder was acknowledged by the user inside the calendar-data.

But since the calendar-data is read-only, storing that information is impossible and Thunderbird keeps showing you the reminder over and over again without you having the ability to mute it. I have seen similar behavior in other clients.

Hence the current behavior of removing reminders in read-only calendars is very much still the desired behavior.

**Comment by nursoda** [comment]
You could also use a separate but writable waste calendar.

I also handcraft those ics files, wrote a (very hacky) scripts for them:

```perl
#!/usr/bin/perl
# Usage: tweak_graugelbblau <landratsamt.ics >mitalarm.ics
while(<STDIN>) {
 $l=$_;
 if ($l =~ /DESCRIPTION:(Graue Tonne|Gelber Sack|Papiertonne)/){$l="";}
 if ($l =~ /LOCATION:Meine-Strasse/){$l="";}
 if ($l =~ /END:VEVENT/){$l="BEGIN:VALARM\nTRIGGER:-PT5H\nACTION:AUDIO\nEND:VALARM\n$l";}
 print $l;
}
```

```perl
#!/usr/bin/perl
# Usage: tweak_schadstoff <landratsamt.ics >>mitalarm.ics
while(<STDIN>) {
 $l=$_;
 if ($l =~ /DTSTART/){($datum)=$l=~/(\d{8})/; $l="";}
 if ($l =~ /DTEND/){$l="";}
 if ($l =~ /DESCRIPTION/){
  ($ort,$vh,$vm,$bh,$bm)=$l =~ /DESCRIPTION:.* \((.*), (\d\d).(\d\d).*(\d\d).(\d\d)\)/;
  $l="DTSTART;TZID=Europe/Berlin:".$datum."T".$vh.$vm."00\nDTEND;TZID=Europe/Berlin:".$datum."T".$bh.$bm."00\n";
 }
 if ($l =~ /LOCATION/){$l="LOCATION:$ort\n";}
 if ($l =~ /END:VEVENT/){$l="BEGIN:VALARM\nTRIGGER:-PT1H\nACTION:AUDIO\nEND:VALARM\n$l";}
 print $l;
}
```

**Comment by aslmx** [comment]
> But since the calendar-data is read-only, storing that information is impossible and Thunderbird keeps showing you the reminder over and over again without you having the ability to mute it. I have seen similar behavior in other clients.

True. But i think this is also happening when Thunderbird can not - for what ever reason - save this into the remote. I have my calendar also in TB and regularly i have to acknowledge reminders multiple times until it is applied, also for calendars that are my own and i can read/write to.
