### ISSUE TITLE
Custom illustrations for calendar events / Ability to delete or disable illustrations

### ISSUE THREAD

**Issue by doom3wasagoodgame** [nextcloud/calendar#2148]
**Is your feature request related to a problem? Please describe.**
I don't like the illustrations for the calendar events.

**Describe the solution you'd like**
Being able to delete or change the graphic for events.

**Describe alternatives you've considered**
Replacing the graphics on my server manually, however I don't know how it will play out with snap updates.

**Comment by georgehrke** [comment]
Is there anything in particular about the illustrations that you dislike? 

In case they are too big, see #1956 about making them responsive.

If you want to replace them, just update the files in `img/illustrations`. If you change filenames, remove or add illustrations, you will have to edit `arc/utils/illustration.js`

**Comment by doom3wasagoodgame** [comment]
> In case they are too big, see #1956 about making them responsive.

Thanks, I'll keep that issue in mind if I need to resize, but sizing is great so far.

> If you want to replace them, just update the files in img/illustrations. If you change filenames, remove or add illustrations, you will have to edit src/utils/illustration.js

Awesome, I'll update the images in place, thanks!

> Is there anything in particular about the illustrations that you dislike?

Just something personal.

![img](https://i.imgur.com/pBVST8A.png)

**Comment by georgehrke** [comment]
> Just something personal.

In that case i will go ahead in close this issue.

**Comment by ctag** [comment]
Hi @doom3wasagoodgame I may have a solution.

There are a couple ways to go about this.

### Delete the images

- On the server, move or delete `nextcloud/apps/calendar/img/illustrations`
- When the images are missing, a generic "clipboard" is shown. **This is the functionality I prefer the most.**
- However, I imagine the images will be replaced on app/server upgrade, or it'll cause the upgrade to fail. So don't do this.

### Use an ad blocker

- I can add `myserv.com##.app-sidebar-header__figure` to my uBlock Origin filter list, and it works.
- The result doesn't look good, which could probably be fixed with some additional work.
- However, I can't use an adblocker from everywhere I connect to nextcloud from, so this approach doesn't work for me either.

### Use custom CSS

- Download and enable the [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss) app. Go to `Settings` -> `Theming` and scroll down to `Custom CSS`. Add the new CSS below and save.
- I think this approach is the best compromise.

```
#app-sidebar .illustration-header, .event-popover .popover-inner .illustration-header {
  height: 50px;
}

div.illustration-header svg {
  display: none;
}
```

**Comment by doom3wasagoodgame** [comment]
@ctag thanks a lot! I'll keep those solutions in mind if I decide that changing the illustrations gradually is too much work. So far it's not a problem.
