### ISSUE TITLE
Email notification upon event creation only

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/calendar#2194]
In the NC settings it is only possible to set email notifications upon "edit of a calendar event". This results in email notifications every time a client syncs this event even if no changes are made to the event. This produces unnecessary emails. I find it very useful to receive an email upon "creation of a calendar event". So maybe you could introduce such an additional option into the settings just like it is already implemented with files: There you have separate options for file creation and file edit. Would make much sense. ;-)

After all, thanks for your great app!!

-Jolopu

**Comment by georgehrke** [comment]
> This results in email notifications every time a client syncs this event even if no changes are made to the event.

This definitely sounds like a bug, not the expected behavior. 
I do not exactly understand what setting you are referring to? Some admin Setting? A setting in the activity app? 

Either way, this repo is the wrong place.

Please open a bug report in the Server repo: https://github.com/nextcloud/server and **fill the entire issue template**

Please link the new issue once you created it. thx
