### ISSUE TITLE
Copy public calendar URL as http(s) instead of webcal(s)

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#2197]
Most tools probably support `http(s)` and [some tools](https://www.reddit.com/r/NextCloud/comments/g2txyb/im_trying_to_get_my_nextcloud_calendar_ical_feed/fnor5b4) don't work with `webcal(s)`, so let's not use this prefix.

**Comment by georgehrke** [comment]
The benefit of having a clickable `webcal` link is that the URL handler will automatically open the `add calendar subscribe dialog` in the user-preferred calendar client.

**Comment by kaleb** [comment]
I can already copy calendar link as http(s) URL. Am I missing something? i get three types, webcal, http, and embed.

**Comment by Bellusterra** [comment]
Just thought I would revisit this, I’m not sure what the plan is, but the subscription link still does not function as intended being a webcals link rather than webcal. I don’t know the protocol for webcals vs webcal and why ios safari doesn’t recognize the former, but Nextcloud uses the webcals link which still does not function as a subscription link.

**Comment by tcitworld** [comment]
Since there's not much traction for this issue, I'm closing it.

@kaleb http refers to the web view, not the direct link to the calendar data

@Bellusterra This is fixed in #3212
