### ISSUE TITLE
Calendar gets deleted when task list is deleted (And vice versa)

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/calendar#2349]
The other day I deleted a task list I did not need anymore. Nextcloud did what I wanted... Some minutes later I figured that I also deleted a calendar with important stuff in it that had the same name. So, apparantly, there is a strong connection between calendars and task lists which is not too obvious to the user. I was lucky enough to be able to restore my lost data from a database backup that my server creates for me every night. But for some other users this might really be a problem. AND: this is a problem that can be avoided.

My suggested solution on this issue:

EITHER warn the user that when he deletes task list X, he will also delete calendar X (also vice versa, of course).
OR: Split calendars and task lists completely. I personally do not see why a connection between calendars and task lists is a good idea. So I'd go this route.

**Comment by raimund-schluessler** [comment]
> EITHER warn the user that when he deletes task list X, he will also delete calendar X (also vice versa, of course).

We do already warn the user when he deletes a task list:
<img width="505" alt="warning" src="https://user-images.githubusercontent.com/2496460/85057401-ff0ac100-b1a0-11ea-8609-efa0fe594244.png">
but we also agreed in https://github.com/nextcloud/tasks/issues/212 that this is not "annoying" enough, since obviously no one reads it. We will change this to a modal asking if you really want to delete the task list and all events and tasks (which likely will still be ignored :wink:).

> OR: Split calendars and task lists completely. I personally do not see why a connection between calendars and task lists is a good idea.

We also do this already. The Tasks app creates tasks-only lists, they don't show up in the Calendar app as calendars at all. The Calendar app lets the user decide whether one wants to store events only or both events and tasks:
<img width="234" alt="selection" src="https://user-images.githubusercontent.com/2496460/85057950-b1db1f00-b1a1-11ea-93e9-937f58762f8f.png">
For already existing calendars which can store both events and tasks there is nothing we can do, as the iCal specification RFC 5545 explicitly forbids to change the calendar components after calendar creation (which makes sense for several reasons).

I will close this issue here, since the modal for Tasks is tracked in https://github.com/nextcloud/tasks/issues/212 already.

**Comment by ho1ger** [comment]
Interesting. I did not see this. So this might support what you wrote... But did you also consider that you can delete a calendar or task list via a (caldav) client, i.e., not the web ui?

**Comment by raimund-schluessler** [comment]
> But did you also consider that you can delete a calendar or task list via a (caldav) client, i.e., not the web ui?

Well, yes, we are aware of that. But we cannot influence how other CalDAV clients treat these cases. Since the Calendar and Tasks app are only CalDAV clients themself, we cannot forbid to delete a calendar via CalDAV. Otherwise it would not be possible to delete calendars anymore at all.

**Comment by nousernameavailableanymore** [comment]
The same thing happened to me at some point.
This is when I learned that the "nextbackup" app is utterly broken as it does not support certain database field types (which are used in the calendar tables) and will wipe your calendar tables before failing to restore them, resulting in a completely broken calendar!

1. Calendars and Tasks should be completely separate. They have nothing to do with each other!
2. Nextbackup is broken and should be removed from the app store.

**Comment by sirnacnud** [comment]
I was wondering where my main calendar went, then realized I deleted the Task List of the same name a while back.

I think no users would make the connection that deleting one or the other, deletes both.
