### ISSUE TITLE
Sharing calendar with groups: If group name has "/", it is not suggested or found

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/calendar#2371]
**Steps to reproduce** (I hope you can reproduce it?!)
1. have a nextcloud user group that has / in the name (in my case it was something like "green/blue")
2. try to share a calendar with that group
3. the name is not suggested, even if you type the whole name

**Expected behavior**
the name is suggested after typing the first letters.

btw it works as it should when sharing a file

Nextcloud server  18.0.6
calendar app 2.0.3
Firefox 77.0.1

**Comments**
Actually this was not the only problem. Another group with a star in the name and the same first word as the one above with the / in it, lets call it "green*tomatoes", was also not suggested when typing. But when I typed the full name of this group, it appeared, and I could select it for sharing. Weird.

**Comment by caribouW3** [comment]
I noticed the same issue with imported LDAP groups.
I change the name 'owncloud_name' in table 'oc_ldap_group_mapping' for that group (just removed the '/' for a try) it shows up (with the right name, since the search is using LDAP), only the initial import was an issue. Is your group also an LDAP group or a locally defined one?

**Comment by alexanderdd** [comment]
no LDAP, group was created via NC web interface

**Comment by joshtrichards** [comment]
Can't reproduce either case mentioned in the original report across v26-v28 with current `calendar` app versions. I can't find associated PRs off-hand, but appears fixed.
