### ISSUE TITLE
Change first day of the week

### ISSUE THREAD

**Issue by sich97** [nextcloud/calendar#2599]
**Is your feature request related to a problem? Please describe.**
First day of the week is set to Sunday, without the ability to change it.

**Describe the solution you'd like**
The ability to set which day is the first day of the week.

**Describe alternatives you've considered**
None

**Additional context**
The international standard of the first day of the week, is Monday as far as I know.
In Norway (which is the locale I'm using) the first day of the week was Sunday until the 80's. But since then, it's been Monday. I therefore find it wierd that the hardcoded first day of the week is Sunday in the first place.

I'm on NC version 18.0.7, calendar app is on version 2.0.3.

**Comment by SwapFaceL** [comment]
As far as I know it was bound to the language setting you can set in the calendar app or in the general settings.
I chose "German" and my week was always starting on Monday. See the current settings:
![Unbenannt](https://user-images.githubusercontent.com/35925904/94396236-cb591300-0161-11eb-819f-b012e8e3df28.PNG)
However since the last update my calendar displays "Sunday" as first day of the week and it is english, so I assume there is a bug in the calendar. Anyone else experienced the same problem?
![Unbenannt2](https://user-images.githubusercontent.com/35925904/94396326-f9d6ee00-0161-11eb-9ff2-4fb519cd8988.PNG)

But I agree it would be an enhancement to set the first day of the week independent on the locale settings.

**Comment by tcitworld** [comment]
> However since the last update

Could you please provide version and configuration details here?

**Comment by SwapFaceL** [comment]
Version is now 19.0.3. What configuration details do you need?

**Comment by sich97** [comment]
I'm on NC 18.0.7, calendar app is on version 2.0.3.
It's been like this for a year now.

**Comment by AlexanderBurker** [comment]
I've just stumbled on this issue because the weekday in my instance was also previously set to sunday. Changing the locale (`Gebietsschema` field in the screenshot above) in my user settings from _dont know (probably EN_US)_ to DE_AT worked as a solution. 

Maybe you need to switch to a different locale once, then switch back? 

NC 19.0.3, Calendar 2.0.4

**Comment by sich97** [comment]
> I've just stumbled on this issue because the weekday in my instance was also previously set to sunday. Changing the locale (`Gebietsschema` field in the screenshot above) in my user settings from _dont know (probably EN_US)_ to DE_AT worked as a solution.
> 
> Maybe you need to switch to a different locale once, then switch back?
> 
> NC 19.0.3, Calendar 2.0.4

This worked for me as well.
Thanks.

**Comment by SwapFaceL** [comment]
I am using NC 19.0.3 and Calendar 2.0.4 as well, however changing setting to US (first weekday sunday) and back did not work in my case. Any other ideas?!
