### ISSUE TITLE
Render multi-day events as all-day events

### ISSUE THREAD

**Issue by jas4711** [nextcloud/calendar#2672]
I have a couple of recurring events that span multiple days, for example a 7 day event spanning Sunday 4pm to Sunday 4pm every other week.  In the calendar view, the app does not render this as a an 'all-day' event on (for example) Tuesdays, instead it is rendering it as a in-day event spanning the entire day.  This makes the calendar view almost unusable for display.  I have "solved" this by moving these events to a separate calendar, and hiding that calendar from view, but it is a workaround.

The logical improvement to solve this appears simple: when rendering an event that spans the entire day, render it as a all-day event rather than occupying the 00-24 part of the display.

I'm attaching a screenshot so you can see how it looks like.
![Skärmbild från 2020-10-27 09-02-10](https://user-images.githubusercontent.com/531817/97273076-251d2d80-1833-11eb-92f8-33401228fbce.png)

**Comment by Torenga** [comment]
If the event is set as "All day", it's displayed in the top row (like your Höstlov). IMO multi-day events with a start- and due_time_ represents an event that doesn't start until X and doesn't last longer than Y. Those two timestamps are usually significant and should be displayed.

If anything, the days between start and stop days are essentially "All day" and could be displayed as such in the top row but I imagine it would be visually confusing.

**Comment by raimund-schluessler** [comment]
I don't think we should change anything here. If one wants multi-day events to be shown as all-day one should simply check the `all-day` toggle. Only showing the "middle" days as all-day is confusing in my opinion as it would appear like different events.

**Comment by bi-on** [comment]
The problem with toggling "all-day" is that you loose the start and end time.

Google calendar displays multi-day events as all-day events since quite a time now, so many peole are used to it (and like it), but I understand your arguments, too.

I see two ways to solve the challenge:
- Global or by-calender setting how to display multi-day events.
- A toggle "Display as all-day" stored in a custom flag, so you could opt in by event.

Which one is preferable in your opinion? The first one would already be helpful, while the second option is more flexible... You could also start with the first one and later on, if requested, the setting could be changed to a "default value" for events.
