### ISSUE TITLE
Field for choosing display format only visible when pointed at 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/calendar#2736]
The field for choosing display format (day, week, month, event) is not visible by default. It gets gray only when you point to it. It does not show which format is active. This is annoying if you look for where to change display format. This is a problem, especially in the mobile phone. It should also show the current format used.

Not sure if it should be called a bug. 

NC20.0.3, calendar 2.1.2

**Comment by raimund-schluessler** [comment]
Could you please post a screenshot of your issue. It is not really clear to me, what you mean. In case you mean the button to select month/week/day, this is visible by default. If it is not visible in your case, then there might be a problem with your instance.

![Screenshot_2020-12-11 Woche 50 aus 2020 - Kalender - Nextcloud](https://user-images.githubusercontent.com/2496460/101882303-fca88300-3b95-11eb-9538-baebf2b32334.png)


In any case, please fill the entire issue template, otherwise we won't be able to help you.

**Comment by rollanders** [comment]
Its odd. Now when I want to reproduce the issue it is not present. Before that I deactivated some apps and activated others. I dont know if that did something. Anyway it is OK now.
