### ISSUE TITLE
Dashboard: user time zone not respected

### ISSUE THREAD

**Issue by dmzh22** [nextcloud/calendar#2858]
### Description
Events in the calendar widget of nextcloud's dashboard are shown in UTC rather than in the time zone the user has chosen in the calendar

### Steps to reproduce
1. Set the time zone of the calendar under calendar --> settings
2. Create an event with a start (and end) time
3. Open the dashboard with the calendar widget. The event will be shown in UTC (at least in my case) rather than in the selected time zone CET as in the calendar app.

### Expected behaviour
Dashboad widget should use the time zone as set by the user in the calendar app (or dashboard widget should be configurable as well)

### Calendar app
**Calendar app version:** 2.1.3

### Client configuration
**Browser:** Firefox 85

**Operating system:** Mac OS Catalina

### Server configuration

**Operating system**: Linux

**Web server:** litespeed

**Database:** MySQL

**PHP version:** 7.4.12

**Nextcloud Version:** 20.0.6

**Comment by miaulalala** [comment]
Dashboard no longer shows date but "in x hours" or "in x days"

**Comment by thederputy** [comment]
This is still an issue as of Nextcloud version 31.0.7, Calendar version 5.3.8.

Dashboard showing  "in x hours" or "in x days" instead of a date still needs to have the calculation based on the correct time zone. It seems like it is currently calculated based on the assumption of UTC, regardless of the time zone of the calendar event.

Example:

An event starting at 9AM on 2025-08-09 in America/Vancouver time zone will show on the Dashboard as "tomorrow" from 5PM onwards on 2025-08-07 in the America/Vancouver time zone.
