### ISSUE TITLE
Upcoming events widget + "create a new event" page does not respond

### ISSUE THREAD

**Issue by emrahyildirim** [nextcloud/calendar#2960]
Apart from the administrator account, when newly opened users log in, click on the dashboard to add new activity from the upcoming events tool, and after a while this page does not respond... waiting or exit page options are coming... The administrator account is functioning properly.

The same problem occurs when opening events added to the calendar from upcoming events in the dashboard. page does not respond

widget upcoming events does not work at all

Security & setup warnings
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the linked documentation for more information.

All checks passed.
Check the security of your Nextcloud over our security scan ↗.

Version
Nextcloud 21.0.0

Your version is up to date.Update channel: Stable

**Comment by wiswedel** [comment]
I can reproduce the behavior when "Enable simplified editor" is configured.

![image](https://user-images.githubusercontent.com/1804221/112323251-e55b5480-8cb1-11eb-9ec0-7de1e3e49fe1.png)

@emrahyildirim Can you please check if you can confirm this too?

**Comment by GretaD** [comment]
The result of the log:
![calendarerror](https://user-images.githubusercontent.com/12728974/113850260-90800980-979a-11eb-89c1-e98829fd2e19.png)




After i click kill,it shows this error: [12873:4:0407/112333.717368:ERROR:child_thread_impl.cc(323)] Crashing because hung

**Comment by st3iny** [comment]
I just tried to reproduce on latest master and it worked fine on Firefox. On Chromium it broke. IMO, this might to be a bug with Chrome/Chromium.

**Comment by ChristophWurst** [comment]
That was also our conclusion last time. Chrome crash logs also didn't reveal any more details.

**Comment by wokawoka** [comment]
@ChristophWurst Since disabling the calendar simplified editor would be an effective workaround to avoid this bug, do you by chance know how I could occ apply this setting recursively for all the users of our installation?

I have found some hints on [this github issue](https://github.com/nextcloud/calendar/issues/3889) (sorry for the multiple crossposts but we need to fix this problem as soon as possible!) but I was not able to achieve to batch change that setting for all our users, who lately are complaining a lot about this but.

Any idea? Thank you very much!
