### ISSUE TITLE
The time-slot I select while in day/week preview, disappears when i click the event title

### ISSUE THREAD

**Issue by GretaD** [nextcloud/calendar#2968]
### Steps to reproduce
1. Change the view to week or day
2. Select a time you want
3. Click anywhere on the popup

### Expected behaviour
The time i select shows all the time

### Actual behaviour
The time i select goes away
![time_week_day](https://user-images.githubusercontent.com/12728974/112284360-723de800-8c89-11eb-8003-061211747889.png)

### Calendar app
**Calendar app version:** master

**Comment by nvindice** [comment]
This problem is huge! We use the calendar for a covid center with 5 minute timeslots in weekly view - this behaviour makes the calendar very hard to use. Each time an event is added, the view jumps back to 6am.

**Comment by nvindice** [comment]
Hi @GretaD, as we really struggle with this issue, I was hoping you could point me into the right direction to look for the root cause of this issue. You seem to know the code a bit (looking at your PRs), I have never looked into nextcloud/calendar before. If I find some spare time I would make a PR to fix this issue myself, but I just don't know where to start and have only very limited time. Thanks for any hint!

**Comment by GretaD** [comment]
Hi, @nvindice. Im really sorry for the late reply, i was on holidays on April and this notification got lost. 

First, you will need a development environment on your machine to start pushing PRs. ([Link](https://docs.nextcloud.com/server/latest/developer_manual/getting_started/devenv.html)) 

We also have a public Talk channel([Link](https://cloud.nextcloud.com/call/5qb8fujz)), where we discuss stuff related to Groupware apps, including calendar. I would be very happy to help you out set up a development environment so you can test stuff whenever you have the time. 
I will have a closer look as soon as i can to this issue, but that shouldnt stop you setting up a dev env and check stuff on your own.

**Comment by nvindice** [comment]
Hi @GretaD, thank you. I guess I did not make myself very clear, sorry for that. I do know how to create a PR, I just have no clue about the nextcloud/calendar code.

But, we moved to another calendar solution in the meantime, so we don't need a solution for this problem anymore. However, I still think this issue is really annoying and needs to get fixed ASAP. I just don't have any resources left to do it.

**Comment by GretaD** [comment]
> Hi @GretaD, thank you. I guess I did not make myself very clear, sorry for that. I do know how to create a PR, I just have no clue about the nextcloud/calendar code.
> 
> But, we moved to another calendar solution in the meantime, so we don't need a solution for this problem anymore. However, I still think this issue is really annoying and needs to get fixed ASAP. I just don't have any resources left to do it.

I see, ok, we will have a look. @st3iny already took over it :)
