### ISSUE TITLE
Importer should assign random UID to events without UID

### ISSUE THREAD

**Issue by Excpt0r** [nextcloud/calendar#3072]
Looks like the random UID generation works only with one entry in .ics but not many.
Related closed ticket: #857

### Steps to reproduce
1. Import the attached example.ics as calendar
[example.ics.log](https://github.com/nextcloud/calendar/files/6455404/example.ics.log)

### Expected behaviour
Calendar entries shall be imported

### Actual behaviour
Calendar Import fails:
`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
  <s:message>Validation error in iCalendar: A calendar object on a CalDAV server may only have components with the same UID.</s:message>
</d:error>
`

### Calendar app
**Calendar app version:** 2.2.1

### Client configuration
**Browser:** Firefox 88

**Operating system:** Kubuntu 20.04

**Comment by tcitworld** [comment]
This is handled in `calendar-js`: https://github.com/nextcloud/calendar-js/blob/master/src/parsers/repairsteps/icalendar/icalendarAddMissingUIDRepairStep.js

**Comment by diego-treitos** [comment]
Actually I think what is happening is the other way around.

https://github.com/sabre-io/vobject/blob/d8a0a9ae215a8acfb51afc29101c7344670b9c83/lib/Component/VCalendar.php#L478

Here there is a check for the number of UIDs that the calendar has and for some reason that I ignore, a DAV calendar can only have components with the same UID. So when you generate random UIDs for each event, I think you are actually triggering this error.

Maybe what is required in orther to import these calendars, is to split them in components after upload and them import the components separatedly. 

It is a shame that we cannot import calendars due to this error.

**Comment by miaulalala** [comment]
We can't tell if the VEVENTs are in any way related to each other if multiple VEVENTs don't have a UID.

Tehcnically speaking a VEVENT without a UID is invalid, so the excection is correct.

If you know these events are NOT related and you still want to import them, you can manuall edit the ics file and add a UID property to each VEVENT block.

Example:

```
UID:123456foobar
DTSTART;VALUE=DATE:20110801
DTEND;VALUE=DATE:20110802
RRULE:FREQ=YEARLY
DTSTAMP:20210509T092146Z
CREATED:20110801T200816Z
DESCRIPTION:
SUMMARY:Example Event2
END:VEVENT
```
