### ISSUE TITLE
Free/Busy should show the organiser's free/busy times as well

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3112]
Currently, the organiser is not show in the Free/Busy overview.

TO DO:

- [ ] Add the organser's free/busy overview here:
![image](https://user-images.githubusercontent.com/7427347/119659967-00238400-be2f-11eb-8e26-75da5fea1dba.png)

**Comment by ChristophWurst** [comment]
We should probably also show the organizer in the sidebar as soon as the first attendee is added to the event. This will take some confusion about why you can't add yourself to the event.

**Comment by st3iny** [comment]
> We should probably also show the organizer in the sidebar as soon as the first attendee is added to the event. This will take some confusion about why you can't add yourself to the event.

AFAIK, this is already implemented:

https://user-images.githubusercontent.com/1479486/120315232-664f5180-c2dc-11eb-8fa2-f79d7326ac07.mp4

**Comment by ChristophWurst** [comment]
Indeed.

on a side note the overlapping status circle vs the participation circle are not ideal. We might want to move the participation icon to the left? cc @nimisha-vijay

**Comment by ChristophWurst** [comment]
-> new ticket https://github.com/nextcloud/calendar/issues/3136

**Comment by nimisha-vijay** [comment]
Can made do, but it looks a tiny bit cluttered, because the sizes are relatively big

![image](https://user-images.githubusercontent.com/52440189/120354001-bef40e00-c31f-11eb-915d-11f148412eb4.png)

Maybe top left? What do you think?

![image](https://user-images.githubusercontent.com/52440189/120355794-3c6c4e00-c321-11eb-903f-32fd5d223541.png)
