### ISSUE TITLE
Availability icon overlaps user status

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3136]
When you add Nextcloud users to your event and they are online, there will be a status indicator in the bottom left of their avatar. This is also where we overlay the avatar with the availability circle.

![Bildschirmfoto von 2021-06-01 17-33-34](https://user-images.githubusercontent.com/1374172/120350709-82b0b580-c2ff-11eb-94ba-027e9942eb82.png)

---

The overlapping status circle vs the participation circle are not ideal. We might want to move the participation icon to the left? cc @nimisha-vijay

_Originally posted by @ChristophWurst in https://github.com/nextcloud/calendar/issues/3112#issuecomment-852135061_

**Comment by nimisha-vijay** [comment]
(oops, didn't see that there was a new issue)

Can made do, but it looks a tiny bit cluttered, because the sizes are relatively big

![image](https://user-images.githubusercontent.com/52440189/120354001-bef40e00-c31f-11eb-915d-11f148412eb4.png)

Maybe top left? What do you think?

![image](https://user-images.githubusercontent.com/52440189/120355794-3c6c4e00-c321-11eb-903f-32fd5d223541.png)

**Comment by tcitworld** [comment]
Even with a different position, I kind of find it confusing, since we have the same set of colours (symbols are different though).

If we want to keep the status indicator, what about using a second line below the attendee name to display in plain text the attendee role and status, kind of what we do with the user status in Talk?

cc @nextcloud/designers

**Comment by nimisha-vijay** [comment]
Actually, that's correct, a subline would may be better. 

Do you mean in plain text like this?
![image](https://user-images.githubusercontent.com/52440189/120442341-1dae9b80-c3a3-11eb-9b54-f462f148e7ba.png)

I think there isn't much of a difference between "No response" and "not attending"
What if we used a subtler version of the icons like this? (30% opacity for bg, full opacity for icon)
![image](https://user-images.githubusercontent.com/52440189/120444021-da552c80-c3a4-11eb-901d-73c97cefc623.png) 

We can also do this (I like this better because the text is all aligned)
![image](https://user-images.githubusercontent.com/52440189/120443888-b98cd700-c3a4-11eb-926a-8be38161cf59.png)

My only concern is that it may be a little bit too present. What do you think?

**Comment by tcitworld** [comment]
I think I prefer the second option.

I also suggested earlier to put the role in the subline as well but I don't see where it would fit now, so that's okay.

**Comment by ChristophWurst** [comment]
Second option looks great :+1:

**Comment by jancborchardt** [comment]
Great proposal with the subline @tcitworld and very nice mockup @nimisha-vijay – agree the second option looks great. :)
