### ISSUE TITLE
Arrow button next to event title in sidebar doesn't do anything

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3160]
### Steps to reproduce
1. Create an event and save it
2. Open the sidebar of this event
3. Change the title
4. Click the arrow next to it

![Bildschirmfoto von 2021-06-07 09-00-30](https://user-images.githubusercontent.com/1374172/120973259-fbd06280-c76e-11eb-8657-0fab648539f5.png)

### Expected behaviour

I actually don't know. Save just the title? It's a bit strange to have the generic save button on the bottom and this one here, but I have no other explanation.

### Actual behaviour

The button should work, or more likely just be removed. I suggest the engineer who takes a look first finds out what the button did, then we decide if removing or fixing is more appropriate.

### Calendar app
**Calendar app version:** 2.3.0 (current master)

cc @GretaD @st3iny @nimisha-vijay

**Comment by raimund-schluessler** [comment]
This button comes from the vue components and emits and event that the title was set, see https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppSidebar/AppSidebar.vue#L515-L523

Since you don't use the `submit-title` event and the visibility of the input is not toggled either, I guess it's fine to hide the button. The alternative would be to toggle the visibility of the title input and save the title only when the button is clicked.

**Comment by ChristophWurst** [comment]
> The alternative would be to toggle the visibility of the title input and save the title only when the button is clicked

I think the problem with that is that events can't be partially saved. Like say the user assigned a new location, then changed the title and pressed the arrow button. Would we save all changes or just the title change?

IMO it's less confusing if only the one general save button at the bottom is used.
