### ISSUE TITLE
Editing repeating events is broken for events with fixed repetition count

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3283]
A user creates a repeating event, everyday, 3 times. It shows 3 events, one each day.

The user modifies the 2nd occurrence and changes the subject of the event, for example and then ask the change to be made for this occurrence and the following occurrences.

The user expects the 2 last occurrences of the event to be modified with the change but actually, there are now 4 events. The first one is unchanged. The next events do have the change, but an additional occurrence has been attached.

The original repetition was erroneously applied to the modified occurrence and an extra occurrence was added.

**Comment by miaulalala** [comment]
@GretaD  could you please test if you can use this feature? Seems like it is completely broken for me, as in I can't update any future reoccurrences at all.

**Comment by GretaD** [comment]
I can reproduce this.

**Comment by miaulalala** [comment]
Thanks Greta!

**Comment by st3iny** [comment]
This works fine for events with a fixed end date for the recurrence. Only events with a fixed repetition count seem to be affected.

Here is some inspiration for fixing the issue I discovered while developing https://github.com/nextcloud/calendar/issues/3282:
I think the problem is that forked recurrence items always inherit the the full recurrence count from the master. Instead, it should be decremented for every instance.

**Comment by miaulalala** [comment]
@st3iny Thanks for your comment, this is very useful to know!
