### ISSUE TITLE
Timezone not taken into consideration when estimating time left before event

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/calendar#3421]
Current time: 08:00 CEST
Event start: 09:00 Mexico City

States: 'In an hour'

![image](https://user-images.githubusercontent.com/14975046/129847065-8ce772e4-585c-4947-82ac-09f67d1c4f04.png)

**Comment by 0xFurqan** [comment]
@st3iny There is no visibility for the event's original timezone in the edit popup at a single glance. 
We can only see the original timezone when the timezone globe icon is clicked. 

It would be great if the event's original timezone was shown somewhere by default without the need for clicking globe icon since the time left is shown by default ( which is calculated based on the original timezone and the users current time ). 

So if we show the original timezone somewhere by default i guess we will have some context about the calculation of the time left being shown.
