### ISSUE TITLE
"Invitation sent." has nothing to do with whether an invitation is sent or not

### ISSUE THREAD

**Issue by Perdex** [nextcloud/calendar#3433]
There's two different ways how it's apparent that the "Invitation sent." confirmation of the calendar has nothing to do with the invitation email actually being sent; however the second problem is very likely a different ssues so I'll report it separately and add the reference here as soon as reported

### Steps to reproduce
1. Open Nextcloud Calendar in the browser
2. Create a new event using the non-minimized editor
3. Name the event "First event"
4. Add an email as an attendee
5. The UI says "Invitation sent." under the email (see image below)
6. Time point 1: No email is received by the invited email address
7. Change the event title into "Second event"
8. Save event
9. Time point 2: Email is received with the title "Second event"

![image](https://user-images.githubusercontent.com/6844274/131131362-7d85c3bf-8850-44b0-b06e-9d09b82d7504.png)

### Expected behaviour
Based on the UI, there should be an invite coming to the email address with the title "First event" at Time point 1, and possibly an update at Time point 2

### Actual behaviour
The email is received at Time point 2 with title "Second event"

### Calendar app
**calendar version:** 2.3.1

### Client configuration
**Browser:** Firefox 91.0.2

**Operating system:** Manjaro Linux

### Server configuration

**Nextcloud Version:** 21.0.3

**Updated from an older installed version or fresh install:** Autoupdated by Snap

**Comment by PVince81** [comment]
I agree, this is *scary* because you're not done yet, maybe just drafting, but you believe that the person has already been invited and start wondering whether you should contact the person to tell them that you didn't intend to setup the event just yet. Perhaps you were just checking if the people in question have time using the "show busy times" button.

And sometimes you might pick the wrong person and you are unsure whether the person already got the invitation or not.
