### ISSUE TITLE
Create Notification for Organiser when booking is confirmed / cancelled

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar#3630]
Currently, the appointment owner ( = organiser) has no way to know which slots have been booked unless they check their calendar. It would be nice to have an event notification for each confirmed booking. 

Thinking a bit further, this could also be useful in case a booking user decides to update their PARTSTAT from Calendar et al directly. As we don't offer a "Cancel booking link" at the moment, this is not unlikely to happen.

This will allow the organiser to be more cognisant of their appointments.

Example
![](https://user-images.githubusercontent.com/925062/137145105-de44f6e8-2a74-4bb7-afe3-bd10ee5337e5.png)

**Comment by schiessle** [comment]
Just as a quick note, because it isn't mentioned explicitly (although I expect that this is the way it will be implemented): It would be nice if users can chose in the notification settings (similar to other already existing events) whether they want to get a mail notification, a push notification or both.
