### ISSUE TITLE
Deleted reoccuring calendar entry still in DB

### ISSUE THREAD

**Issue by mkriegl** [nextcloud/calendar#3797]
I deleted a reoccuring calendar entry in Nextcloud, but it seems still do be in the database. 
My problem is, that I am having a ICS export and a display showing the upcoming events. In that view and als in the ICS download the deleted reoccuring calendar entry is still showing up, but I cannot see it in Nextcloud Calendar anymore. I would like to delete it completely from the database, to not show up anymore

**Comment by ChristophWurst** [comment]
Likely because of https://docs.nextcloud.com/server/23/user_manual/en/groupware/calendar.html#calendar-trash-bin but not sure because I have no information about Nextcloud version, app version or anything else.

If that trash bin is the issue please open a full bug report following https://github.com/nextcloud/calendar/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=
