### ISSUE TITLE
Blocking timeslots of other calendar's appointments

### ISSUE THREAD

**Issue by faulix** [nextcloud/calendar#399]
I need a feature which shows timeslots automatically blocked when there is an appointment in an other calendar. The background is I use several calendars for different reasons and I need one master-calendar in which all timeslots are shown as busy, which are busy in one of the other calendars.

So I would like a option to reference in the settings of calendar1 to a calendar2 and when there is an appointment marked as "show as busy" in calendar2, then this timeslot should also be shown as busy in calendar1.

An alternative to this would be to have a virtual "summarized calendar" (sharable), which automatically merges all appointments of the other calendars.

**Comment by georgehrke** [comment]
> I need a feature which shows timeslots automatically blocked when there is an appointment in an other calendar. The background is I use several calendars for different reasons and I need one master-calendar in which all timeslots are shown as busy, which are busy in one of the other calendars.

Why not simply display all calendars?

**Comment by faulix** [comment]
Yeah I should have mentioned that before: The virtual import/summary/whatever should import privately, which means it should just show a placeholder and now details. By this people know I'm not available but they don't know what I'm doing (my private stuff).

**Comment by georgehrke** [comment]
Ah, you want to share that calendar.

What you are looking for is https://github.com/nextcloud/calendar/issues/39

**Comment by faulix** [comment]
But it's not the same. Because with that everyone knows from which calendar the appointment comes. I want to have it "merged" that it's not possible anymore to distinguish from which calendar the appointment is.

**Comment by georgehrke** [comment]
We will go with Free-Busy, because that's the standardized way and supported by various different clients.

**Comment by tuckcodes** [comment]
Was this actually solved for? This is very valid, and the core feature behind startups like usemotion, reclaim.ai, and calendarbridge.

Problem: Double booking due to lack of bidirectional calendar sync.

UX/story:
I sync my personal Google calendar. 
I then sync my O365 work calendar. 
I have yoga at 11 AM on my personal calendar.
My work calendar shows "busy" with no details, but has 11 AM blocked due to the personal calendar.
My boss schedules a 1:1 for 3 PM tomorrow.
My personal calendar then shows "Busy(custom label)" for 3 PM that day.

Justification:
Though I have multiple calendars (three actually), I only have one of each hour. Therefore, the calendars are funnels into a pipeline of "so many hours in a day". If one calendar is leveraged to book an appointment, the other calendars should be prevented from 'double booking'.

Examples:
1. Calendarbridge
2. reclain.ai
3. usemotion
