### ISSUE TITLE
Ability to remove certain menu options on Calendars entries

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/calendar#3993]
### Is your feature request related to a problem? Please describe.

On Shared environments notifications make less sense than on dedicated and with shared environment/devices Download confuses users since there is no use for that in general since everything is done "online"

### Describe the solution you'd like

Ability to remove some menu items in Calendar app to avoid user's confusion (i.e., the functions that not applicable an certain/shared environments). 

1. Remove the "Download" button inside Event's Details:

![image1](https://user-images.githubusercontent.com/1315170/151061505-037ccc02-ab5e-4bfe-b275-0fb0c9cf4394.jpeg)

2. Remove the "Notification" and set "Email" by default in the Event details->Reminder (added a reminder first):

![image2](https://user-images.githubusercontent.com/1315170/151061519-b7b981bb-7b0c-407b-a5c0-ee214e130996.jpeg)

---

> Remove the "Notification" and set "Email" by default in the Event details

Design-wise, both of these could be removed. The method of reminder should be a user setting to be put in the "Notifications" user settings, which could be set to mail, push, neither or both. Default should probably be both, cause mail covers the folks which don’t have Nextcloud open all day every day:

![image](https://user-images.githubusercontent.com/925062/151171010-65e94f7d-d553-4907-8168-10f5eff71ad1.png)

> Remove the "Download" button inside Event's Details

Can understand that, even for us this is more of an advanced "Export" function which is not so important?

### Describe alternatives you've considered

no

### Additional context

no

**Comment by szaimen** [comment]
Could this ability be somehow wrapped into a config setting? For the normal user are these options very useful...

**Comment by AndyScherzinger** [comment]
> Could this ability be somehow wrapped into a config setting? For the normal user are these options very useful...

Yes, that is the idea 👍

**Comment by tcitworld** [comment]
Can you explain more what's shared environments so that I can understand more what are the encountered issues ?

I think renaming the Download buttons to Export makes sense in any case.

On the topic of reminders, some remarks:
* This would apply only to events created through the NC calendar app, not from 3rd-party clients that may have some other reminder defaults settings (or none). Might add confusion if those are not the same than the new global settings.
* Having both email and notification providers enabled as a default seems fine to me, apart from when the reminder is sent ~10 minutes before the event and we've just sent an useless email you'll probably only see during or after the event (email being sent before the start of the event doesn't mean you'll receive it straight away, contrarily to a push notification or your phone's own calendar system).
* If reminder settings were to be moved in the notification settings, they wouldn't be affected by other options on this page, such as the option to pick when digest emails are sent (ASAP/hourly/daily/weekly), so it might add confusion too if they're just another item in the list.

Related issues on the topic of default reminders configuration https://github.com/nextcloud/calendar/issues/629 https://github.com/nextcloud/server/issues/1505

**Comment by AndyScherzinger** [comment]
@tcitworld I can try :)

We face installation where the device mobile phones/tables and laptops are shared resources, so the every 8 hours the device is with somebody else and the interaction with the Nextcloud is purely "only", so the options have confused several users because the features can't really be used thus the idea is to provide 2 config switches to simply hide these actions and options from the menues.

**Comment by ChristophWurst** [comment]
Done via https://github.com/nextcloud/calendar/pull/3995, https://github.com/nextcloud/calendar/pull/3997 and https://github.com/nextcloud/calendar/pull/4015.
