### ISSUE TITLE
The Appointments function does not work well in the Calendar App

### ISSUE THREAD

**Issue by Wotan6891** [nextcloud/calendar#4099]
### Steps to reproduce

hello,

when i try to book an appointment like anyone post using the public link. sends an error:

“Could not book the appointment. Please try again later or contact the organizer.”

could you help me?

Thanks

### Expected behavior

the appointment is sent.

### Actual behaviour

it is not being sent

**Comment by ChristophWurst** [comment]
Hey @Wotan6891.

If this ticket is about a question, please ask it at https://help.nextcloud.com/c/apps/calendar/42.

Otherwise please try your best at creating a ticket with actual reproduction info. Your description leaves that all open and the maintainers will possibly have trouble knowing how you ran into this.

Cheers

**Comment by GogoFC** [comment]
Might need to set up Email server in Groupware.
