### ISSUE TITLE
Drop support for Nextcloud 9 and 10

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#433]
looking at https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#overview
Nc 9 is already dead and Nc 10 will have its End of Life next month.

Therefore I would like to drop support for Nextcloud 9 and 10 with Calendar 1.6.0.
The upcoming 1.5.3 will be the last regular update for Nextcloud 9 and 10.

@tcitworld Do you agree? :)

**Comment by tcitworld** [comment]
I agree to drop the support for them. At what point will we be able to remove [this kind of dirty hacks](https://github.com/nextcloud/calendar/blob/master/controller/viewcontroller.php#L74) ?

P.S : wow, I find the end of lives to come really quick (one must migrate from 9.x directly to 11.x) since both 9.x and 10.x were EOL nearly at the same time.

**Comment by georgehrke** [comment]
Things like `$needsAutosize` and `$supportsClass` are only changing the codepaths in JavaScript, so we can drop this code along with version 1.6.0 :)
