### ISSUE TITLE
Feature request: 2-weeks view (custom views)

### ISSUE THREAD

**Issue by mcorteel** [nextcloud/calendar#524]
I personally don't have any use for the week view and I would really like to replace it with a custom view showing 2 weeks (same as the month view, but showing only 2 rows). What I have in mind is some way to configure the available views (like [google calendar](http://www.scottgreenstone.com/2016/07/google-calendar-custom-view.html) does very badly, but still).
I don't know if it would suit your simplicity criteria but that's worth asking :)

Anyway, thanks for a great app!

**Comment by georgehrke** [comment]
Being able to configure custom views is really an overkill in my view. cc @jancborchardt 

What's your use case for a two week view? 

My vision is to eventually have continuous scrolling in both week and month view and that the week view would start at the current day instead of the last Monday / Sunday.

**Comment by mcorteel** [comment]
My use case is that I have a lot of calendars (work, shared with my wife, etc). In the month view, some days will have too many events to display them all without the view overflowing (which doesn't look good).
And I usually don't need to see events more than a week in advance but I like to see what I'm doing this week-end and the next.

**Comment by georgehrke** [comment]
Do you think about a grid view (like month) or an agenda view (like week)?

**Comment by mcorteel** [comment]
It would definitely be a grid view for me. I really have no use for an agenda view if the event's time is visible right before its title! It actually makes it harder to see what my day's schedule is IMO.

**Comment by georgehrke** [comment]
Hm, so you basically want the month view with only 2 rows instead of 4 or 5?

**Comment by mcorteel** [comment]
Exactly!

**Comment by georgehrke** [comment]
So what is the benefit over the month view? 

Especially once we have https://github.com/nextcloud/calendar/issues/6

cc @jancborchardt

**Comment by mcorteel** [comment]
> In the month view, some days will have too many events to display them all without the view overflowing (which doesn't look good).

It's just much clearer and removes clutter.

**Comment by jancborchardt** [comment]
I agree with @georgehrke here. Once we have continuous scrolling, the view could show as many weeks as is relevant for you depending on the schedule.

That is,if you have a lot of events each day/week they will make the weeks be very high and extend vertically, so that probably only 3 or even 2 weeks are shown: Giving you the view you want.
For someone who doesn't have as many events, it would be the simple month view.

**Comment by mcorteel** [comment]
Yes, that makes sense!
I'm personally not a big fan of continuous scrolling in calendar views, but that's not the point :)

**Comment by mmeinesz** [comment]
+1
it should not only be limited to two weeks, but to x weeks. See google calendar custom week view.
