### ISSUE TITLE
"More details" of fresh event is broken

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5840]
### Steps to reproduce

1. Click into the calendar
2. Enter an event title in the simple editor
3. Click *Save*
4. Click *More details*

### Expected behavior

Event shows in the sidebar

### Actual behaviour

![Bildschirmfoto vom 2024-03-08 08-05-17](https://github.com/nextcloud/calendar/assets/1374172/89492c66-7902-46ca-9f6a-2aec1f1e6576)

URL is `/apps/calendar/`

### Calendar app version

4.7

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
Regression possibly introduced with https://github.com/nextcloud/calendar/issues/3543

**Comment by executed** [comment]
@ChristophWurst @st3iny 

STR:
1. Simple Editor is disabled
2. There's at least one event on daily view
3. User clicks on an empty time slot
4. User does not fill anything in the revealed sidebar (event is empty)
5. User clicks on other pre-existing event;
6. Sidebar for other pre-existing event reveals;
7. Empty event that user just jumped focus from gets saved as empty
8. User observes title "Untitled event"

Looks like a bug to me as after heavy daily planning sessions you get to clean up bunch of those empty events.
Do you think it was caused by this PR?
Perhaps there's another issue where this bug is being tracked?

**Comment by SebastianKrupinski** [comment]
@executed 

Tested and Confirmed your issue. 

I've started a new ticket for this as not to hijack this ticket.
