### ISSUE TITLE
Removed Single Occurrence of Reoccurring, Confidential Event Remains on Shared Calendar

### ISSUE THREAD

**Issue by Tally** [nextcloud/calendar#5860]
### Steps to reproduce

1. Create a reoccurring event that only shows as "busy" when shared.
2. Share this calendar.
3. Delete an occurrence of this series.

### Expected behavior

The single occurrence is deleted from both the owner calendar and the shared, confidential version of the calendar.

### Actual behaviour

Occurrence is deleted from the owner calendar, but it remains on the shared calendar (but is not listed in the owner trash; I assume it's actually being made invisible).

Changing the reoccurring event to show "full" details when shared, caused the deleted event to disappear from the shared calendar as well.

### Calendar app version

4.6.6

### CalDAV-clients used

DAVx5

### Browser

Brave 1.63.174

### Client operating system

Windows 11

### Server operating system

Raspbian Bookworm

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.1

### Nextcloud version

28.0.3

### Updated from an older installed version or fresh install

Fresh install

**Comment by miaulalala** [comment]
Reproducible on main.

**Comment by Tally** [comment]
I'm still having issues getting congruence between my DAV calendar on my clients and my web calendar in this situation. The most common situation lately is that I can delete a single instance on the CalDAV client (Samsung calendar on Android), which works and is persistent, but the instance remains on the web calendar. Attempting to delete the event on the web calendar is unsuccessful. In fact, at the moment, deleting any single instance of these recurring events on the web calendar is unsuccessful. Considering that my primary use for this calendar is to share my schedule (which is unusual) simultaneously via web or subscription access while being able to modify it from my phone, this is a critical deficiency.

Thanks for the support and your work on Nextcloud generally.

Nextcloud Hub 8 (29.0.7), AIO Dockerized version
Calendar 4.7.16

**Comment by Biepa** [comment]
@miaulalala I'm currently facing the same issue @Tally is mentioning with the exact steps he mentioned.

Nextcloud Hub 10 (31.0.0)

What is needed to get this reopened/in the queue?

**Comment by Biepa** [comment]
@st3iny Could this one be reopened?

**Comment by st3iny** [comment]
@SebastianKrupinski Could you please have a look and try to reproduce the issue?

**Comment by Biepa** [comment]
Thank you. I'm happy to provide any data you need.

**Comment by SebastianKrupinski** [comment]
@st3iny 

Tested on NC 32 dev and NC 31.0.8

- Created event for single hour with 12 occurrences (Mon, Wed, Fri) 
- Shared calendar with User Two
- Deleted single occurrence on Sept 17th

I was not able to reproduce this behavior the event disappeared for both the owner and sharee.

Owner's Calendar

<img width="1919" height="1032" alt="Image" src="https://github.com/user-attachments/assets/84463377-5ec0-4e63-bea9-6ff4b202847a" />

Sharee's Calendar

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/3b1eb8a7-131e-4ced-99a9-203a2cf31d82" />

**Comment by Biepa** [comment]
@SebastianKrupinski
I just tried with a new user and can't reproduce it also.
Maybe the issue is something in the data of the existing calendars?

I'm just looking at an alert that shows up on my phone and the one from my wife but the Nextcloud UI is not showing it.
It is in the ics file when I export the calendar though.

I just exported the calender and imported it again in a "new" calender.
The event still doesn't show up while others are imported without problems. Possibly another issue then?
Is there a log that I could check for possible errors when importing a calender?

**Comment by SebastianKrupinski** [comment]
> I just exported the calender and imported it again in a "new" calender. The event still doesn't show up while others are imported without problems. Possibly another issue then? Is there a log that I could check for possible errors when importing a calender?

Can you share the event details with me? You can sanitize and personal information from it first

**Comment by Biepa** [comment]
@SebastianKrupinski 

As my complete ICS file has over 10 years of events I did multiple tests and cut it down by testing if the issue persists.
If you import this one you can see the Tuesday events in July. But there should be one for 4th of September as well according to the ics file (renamed to txt due to upload restrictions).
The 4th September one is the one showing up on other systems like iPhone without issues.
[ics_file.txt](https://github.com/user-attachments/files/22173716/ics_file.txt)

Thank you for taking a look.
Let me know if you need anything else.
