### ISSUE TITLE
Calendar Subscription not Show on the Nextcloud > Calendar

### ISSUE THREAD

**Issue by extobi** [nextcloud/calendar#5870]
### Steps to reproduce

1. Add a iCal Adress for a Subscription
2. -
3. -

### Expected behavior

The Calendar is in the Left Menu visible, but not shows any Dates on all Months

### Actual behaviour

It' shows in iPhone or other Devices, but not in the Calendar App on Nextcloud

### Calendar app version

4.6.7

### CalDAV-clients used

-

### Browser

Opera (108.0.5067.29)

### Client operating system

macOS

### Server operating system

Ubuntu/Plesk

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP [8.3.4]

### Nextcloud version

28.0.3

### Updated from an older installed version or fresh install

Fresh install

### Log file

```Text
-
```

### Browser log

```Text
-
```

**Comment by extobi** [comment]
in the logs is nothing.

but at the first adding, i don't know really whether it was this log entry:
ParseException
This parser only supports VCARD and VCALENDAR files
Subscription 5 could not be parsed

**Comment by eliba** [comment]
same issue here, personal and local calendars are shown, but subscribed read-only calendars do not show any events. Also no events are shown in either `php occ log:watch` or `php occ log:tail`.

Browser: Firefox 123.0.1
Nextcloud: 28.0.2
Calendar: 4.6.7
Server OS: Debian 11
Webserver: nginx + nginx reverse proxy
PHP: 8.1
Database: mysql 5.8
Fresh install: no, regular updates since >2y

**Comment by extobi** [comment]
still not working...
Nextcloud v28.0.5 and Calendar v4.7.4

**Comment by miaulalala** [comment]
can you confirm the external calendar contains events? This should have been fixed with https://github.com/nextcloud/server/pull/43698

**Comment by extobi** [comment]
Now it's working and showing in booth.

**Comment by extobi** [comment]
Now it's working and showing in booth.
