### ISSUE TITLE
new event does not use Default calendar anymore

### ISSUE THREAD

**Issue by tessus** [nextcloud/calendar#5942]
### Steps to reproduce

1. open calendar app
2. create an event

### Expected behavior

`Default calendar` should be picked and selected (the one that was created first as the deafult calendar)

### Actual behaviour

The calendar that starts with `A` is picked.

This behavior seems to be new after the upgrade to 4.7.0. Previously the default calendar was pivked. Now I always have to manually select the default calendar

### Calendar app version

4.7.0

### CalDAV-clients used

none

### Browser

Firefox 125.0.2

### Client operating system

macOS

### Server operating system

Linux

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.8

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.8.1
  - appointments: 2.0.7
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.7.0
  - calendar: 4.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.3
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.4.7
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.4
  - notifications: 2.15.0
  - notify_push: 0.6.10
  - oauth2: 1.15.2
  - password_policy: 1.17.0
  - phonetrack: 0.7.7
  - photos: 2.3.0
  - polls: 5.4.3
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.19.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.12.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - activitylog: 0.0.2 (installed 0.0.2)
  - apporder: 0.15.0 (installed 0.15.0)
  - dashboard: 7.7.0 (installed 7.0.0)
  - encryption: 2.15.0
  - files_markdown: 2.4.1 (installed 2.4.1)
  - impersonate: 1.14.0 (installed 1.14.0)
  - recommendations: 1.6.0 (installed 0.5.0)
  - support: 1.10.1 (installed 1.4.0)
  - survey_client: 1.15.0 (installed 0.1.5)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.0.1)
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.8.1",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "share_folder": "\/Shared",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logdateformat": "Y-m-d H:i:s O",
        "logtimezone": "Europe\/Vienna",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "integrity.check.disabled": true,
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": false,
        "simpleSignUpLink.shown": false,
        "upgrade.disable-web": true,
        "theme": "my",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "filesystem_check_changes": 0,
        "mysql.utf8mb4": true,
        "connectivity_check_domains": [
            "google.com"
        ],
        "default_phone_region": "CA",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Comment by st3iny** [comment]
We implemented setting a default calendar recently. 

@tessus Please check that the correct default calendar is configured in the calendar settings on the bottom left. Scroll to `Default calendar ...`.

The calendar that is picked by default for new events should match the configured calendar in the settings. If not, there is a bug.

I was not able to reproduce it on 2 separate instances.

**Comment by tessus** [comment]
@st3iny There is no `Default calendar` in my calendar settings.

**Comment by st3iny** [comment]
Ahh right, I just saw that you are on Nextcloud 27.1. I'll give it another test.

**Comment by bcutter** [comment]
Calendar app v4.7.0 @ Nextcloud Hub 7 (28.0.4). Started seeing error messages when trying to create new events in the web. Log says

```
InvalidComponentType iCalendar objects must at least have a component of type VTODO
```

I noticed that a task list is set as calendar. Probably because/since I enabled the "show tasks in calendar" setting (disabled it a minute later). Now the very first task list (named "+++NEW+++") is always preselected when trying to create new events in the (an actual) calendar.

![grafik](https://github.com/nextcloud/calendar/assets/13799156/5d84e226-e0bb-463b-81b2-1819d6dedca7)

I also don't have a default calendar setting (anymore?).

**Comment by nailyk-fr** [comment]
Exact same issue here. 
Happened after the latest update to 4.7.1

Even worse, here it default creating in a disabled calendar. 

![image](https://github.com/nextcloud/calendar/assets/16372405/ff800159-b3c8-4c66-a4aa-302e0acbcc1a)

Can I provide any information to help solving the issue ?

**Comment by st3iny** [comment]
The default calendar option is only shown on Nextcloud 29 and above. It is a fairly recent feature.

Two questions:
1. Did you share your default calendar with someone or a group etc.?
2. Is your default calendar an incoming share e.g. shared with you?

On that note: Does any of the two apply to the calendar that is incorrectly selected instead of your default calendar?

**Comment by bcutter** [comment]
1. No
2. No
Additional question: No.

Seems like the app lacks some kind of backward compatibility (<29), isn't it?

**Comment by tessus** [comment]
> * Did you share your default calendar with someone or a group etc.?
> * Is your default calendar an incoming share e.g. shared with you?

No.
No.

> Does any of the two apply to the calendar that is incorrectly selected instead of your default calendar?

No.

**Comment by sena73** [comment]
I have here 3 nextcloud instances: two 28.0.5 (upgraded from 28.0.3, 28.0.4 recently) and one 28.0.3.

All of them run Tasks 0.15.0 and Calendar 4.7.1

Everything works on 28.0.3 and one of  28.0.5, but not on another 28.0.5! The configuration is pretty the same everywhere. I am getting 'Failed to save event' error and in detailed log 'InvalidComponentType iCalendar objects must at least have a component of type VTODO'

I found that $supportedComponents is set to VTODO in 3rdparty/sabre/dav/lib/CalDAV/Plugin.php

```php
819         if (isset($calendarProperties[$sCCS])) {
 820             $supportedComponents = $calendarProperties[$sCCS]->getValue();
 821         } else {
 822             $supportedComponents = ['VJOURNAL', 'VTODO', 'VEVENT'];
 823         }
```
So when VEVENT comes from the browser, it throws exception because only VTODO is supported. If I leave line  822 only and force $supportedComponents to ['VJOURNAL', 'VTODO', 'VEVENT'], then everything starts working again and I can add events in web-interface again.

Do I understand correctly from previous comments that somehow default calendar becomes of the type task, that does not allow VEVENT entries? Can you please provide some simple quick workaround? Should I change the default calendar?

May be upgrade to 29? But when I want to  upgrade to 29, on the upgrade screen i can see a message "1 app has no compatible version for this Nextcloud version available."  "Tasks"

**Comment by sena73** [comment]
So, resolved here.

1. Upgraded to Nextcloud 29, Tasks app is disabled automatically.  Hope it will be repaired soon. Problem persists at this point.
2. Removed "tasks" calendar and added "default" calendar.
3. Problem resolved.

**Comment by tessus** [comment]
@sena73 upgrading in not a proper solution. I have destroyed working nc instances by upgrading to soon in the past. Thus I usually only upgrade when `x.y.5` is available. But that's besides the point.

The issue here is that **all of a sudden** creating an event via the web UI does not pick my default calendar anymore. Otherwise I would have never hit the issue, because it certainly worked in the past. I just do not know when exactly it stopped working.

**Comment by bcutter** [comment]
> I just do not know when exactly it stopped working.

I think it stopped working with 4.7.0 calendar app update.

**Comment by tessus** [comment]
@bcutter I believe you are correct. It've noticed it around the release of 4.7.0

**Comment by st3iny** [comment]
Thanks for the replies so far. I was able to reproduce it:

1. Create a list withing the Tasks app (will only support `VTODO`).
2. Switch to the Calendar app.
3. Delete the default calendar (should be `Personal` by default).
4. Move the task list to the top in the left sidebar.
5. Reload the page.
6. Create the new event.
7. Observe how the task list (or simply: the first calendar in the list) is selected.
8. Creating an event breaks now because `VEVENT`s are not supported by the collection.

From my point of view it works as intended as the first calendar is picked from the list in case the "original" calendar is deleted.

## For me to investigate

1. Filter calendars that don't support `VEVENT`s in the frontend.
2. Check why it worked before. Could it be that the default calendar url is not respected in that case? AFAIK, we didn't change the logic in the backend if it wasn't configured by the user (which requires >= 29).

**Comment by st3iny** [comment]
I think I found the bug. The default calendar is now determined by the `schedule-default-calendar-URL` sent by the backend.

However, the logic that is used in the backend is not identical to the logic we used in the frontend before 4.7.0 to select the default calendar. E.g. the backend skips shared calendars, ignores if a calendar is disabled and doesn't check if it supports `VEVENT`s.

My proposed solution would be to only use the suggested default calendar from the backend if it makes sense (is enabled etc.) in the frontend and is actually selectable.

**Comment by nailyk-fr** [comment]
> The default calendar option is only shown on Nextcloud 29 and above. It is a fairly recent feature.
> 
> Two questions:
> 
>     1. Did you share your default calendar with someone or a group etc.?
> 
>     2. Is your default calendar an incoming share e.g. shared with you?
> 
> 
> On that note: Does any of the two apply to the calendar that is incorrectly selected instead of your default calendar?

Hello, 

Sorry for being late, somehow, I didn't receive notifications. 
Default calendar is NOT a recent feature. I am using it for very long time. 

The one which is now marked as 'do not use' is the original 'personal' one. 
The 'kittens' which is displayed on top is shared, indeed and not owned by me. Actually, all my calendars belongs to another account. 
The 'before' behavior, was not really a 'default' calendar, but an order. You can drag and drop the calendars, to change the order in which they are displayed. Then, when creating an event, the one on top was offered by default. 
It was in the documentation to do this way. (like explained here in 2021 : https://help.nextcloud.com/t/how-to-specify-the-default-calendar/116907 )
I am not able to diff the commits as I don't see the tags/releases, but I believe the order of the offered list changed from 'sorted' to alphabetical. 

If you can point me to before 4.7.x I can try to search in the commits. 

Best regards

**Comment by tessus** [comment]
Thanks for the fix, but I doubt that this will solve my issue. In the PR you mentioned _Simply use the old logic (first sorted calendar) on older instances._

sorted by what? alphabetically?

I remember that my `Default calendar` (which was created first when I started to use Nextcloud) to be picked as the default even when I had a calendar with a name that started with a letter A, B, or C.

I guess I will have to wait for nc 29 to define a calendar as the default. Not to be an ass, but this is basic functionality. I still think nextcloud has its priorities twisted. It's 2024 and until now it was just hit and miss for a default calendar or you had to create one thst started with `000_`? I am baffled.

I know it is not your fault, but the entire group of nc designers should really work to strengthen (as in make more reliable) and fix the basic functionality instead of creating new (and half baked) features.

**Comment by st3iny** [comment]
> sorted by what? alphabetically?

The way it was before my change was introduced: Sort by the user's custom order (drag and drop in the left  calendar list).

> I remember that my Default calendar (which was created first when I started to use Nextcloud) to be picked as the default even when I had a calendar with a name that started with a letter A, B, or C.

As long as it is on the top it will be picked by default. Again, just as it was before.

> I guess I will have to wait for nc 29 to define a calendar as the default. Not to be an ass, but this is basic functionality. 

The actual logic is implemented in the server repository. The calendar app is simply acting as a frontend regarding this feature. Thus, you need to upgrade to 29 in order to define default calendars as a user.

**Comment by nailyk-fr** [comment]
Hello all, 

No clue if the 2nd commit is also included in the 4.7.4 I just installed, but the behavior is now definitively the same as before for me : 
![Capture d’écran_2024-05-16_13-54-51](https://github.com/nextcloud/calendar/assets/16372405/89924827-3add-4e51-adcd-2ea2d2f5e52e)


(actually, just noticed one calendar is not displayed in the calendar picker :thinking:, but that's another topic and, I don't care, as I am not using that calendar :yum: )

So, in my opinion, this solves the issue perfectly, thanks a lot @st3iny  !

**Comment by bcutter** [comment]
It never was solved the right way. Instead of defining a default calendar to use, now it just uses the first calendar.

So for you @nailyk-fr it just felt like the same behavior as your first calendar luckily matches/matched your "default calendar in mind".

Following up because of #6992.

**Comment by SebastianKrupinski** [comment]
> It never was solved the right way. Instead of defining a default calendar to use, now it just uses the first calendar.

I've put the default calendar selector back.

https://github.com/nextcloud/calendar/pull/8004

If the property is set it should select the defined primary calendar.

https://github.com/nextcloud/server/blob/79d4953e649a6d0fab8ae4f8bd5dce8a9d3124ea/lib/private/Calendar/Manager.php#L300

We're slowly getting there.

**Comment by xaltube** [comment]
The default selector is back, but can only select between own calendars.

Why shared calendars are not eligible as default?

**Comment by SebastianKrupinski** [comment]
Hi @xaltube 

The setting is for inbound calendar invitation... Why would you need to set a shared calendar as your destination calendar for fresh invitations?

<img width="679" height="92" alt="Image" src="https://github.com/user-attachments/assets/ad8a5583-2e12-4842-8665-f9124470121e" />

**Comment by xaltube** [comment]
Hi Sebastian,

Sorry, perhaps I did not fully explain myself.

What I mean is that when creating a new event in the calendar, it creates it by default in the Personal calendar defined as default, but there is no way to define a Shared calendar as default for newly created events.

Probably I got confused by the title, where it is just mentioned "new events", without mentioning the issue refers to the received invitations.

Probably it is better to follow up on this request for finding a way to create new events by default on a shared calendar through #7218 or #6015
