### ISSUE TITLE
Include incoming shared calendars in the "default calendar" selection

### ISSUE THREAD

**Issue by Steinbam** [nextcloud/calendar#6005]
### Is your feature request related to a problem? Please describe.

If a have one or more incoming shared calendars (which I can edit of course...), there is no possibility to select one of those calendars as the "default calender" with the recently introduced setting.
Even more, if I have 2+ own calenders, I am **forced** to select one of those as the default. If there are only shared calendars and I delete the "Personal" calender, the old behavior still applies and the calendar which is top of the list is set as the default. However, it seemed that if I keep the "Personal" calender, this is used as the default and the order of the list is ignored.

### Describe the solution you'd like

To my opinion, the selection of a default calender should include all editable calenders, regardless if they are shared or own calenders. Otherwise, this setting seems to be incomplete and not very helpful. I think it is not unusual that a shared calendar is the top-priority calendar for some users in an organization.

### Additional context

Tested with NC 29.0.0 and calendar 4.7.3

**Comment by miaulalala** [comment]
@st3iny would you be able to take a look?

**Comment by st3iny** [comment]
Yeah, I agree that this might be confusing. The problem is that the scheduling logic breaks in shared calendars so we have to limit the calendar options to owned calendars. This is a limitation inside sabre/dav.

To avoid further confusion we changed the setting to be used only for incoming invitations which are handled by the CalDAV backend. In the frontend, the default calendar options is not longer used and the calendar picker works like before.

Ref https://github.com/nextcloud/calendar/pull/5996
