### ISSUE TITLE
Event with attendees and one attendees changes the date

### ISSUE THREAD

**Issue by kobelka** [nextcloud/calendar#6373]
### Steps to reproduce

1. Create an Event with attendees
2. The attendees changes the Event
3.The Change ist only in the Personal Event of the attendees

### Expected behavior

That the Event of the owner of the Event and the other attendees ist also changed

### Actual behaviour

Only the Event in the Personal calender of the attendees ist changed

### Browser

Chrome

### Client operating system

Windows

### Server operating system

Unraid

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

None

### Nextcloud version

30

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
This is expected behaviour in line with RFC 5545 - only the ORGANIZERs changes are taken into account for properties other than the partstat.

If you think about the implications of

1. not allowing changes to a calendar event for an ATTENDEE 
2. allowing changes to propagate when an ATTENDEE changes the event

it becomes clear why.

For 1. it would mean giving somebody else higher privileges to your own calendar, in this case the ORGANIZER
For 2. it would mean giving the ATTENDEE the same privileges as the ORAGINZER

As the owner of the principal, the ATTENDEE still has the most privileges on a calendar, which includes modifications on a VEVENT, but that doesn't mean those changes are allowed to propagate to other principals.

**Comment by kobelka** [comment]
But if the person invited changes the date by mistake, no one notices (not even him) or he changes it on purpose and thinks everyone knows now. There is no indication that only his own date has been changed.
