### ISSUE TITLE
Excluded recurring event can't be deleted

### ISSUE THREAD

**Issue by ygoe** [nextcloud/calendar#801]
### Steps to reproduce
1. Create a daily recurring event in the Nextcloud calendar
2. Synchronise to Android with DAVDroid
3. Delete one of the middle events from the recurrence (because you can't do that with Nextcloud calendar)
4. Synchronise back to the server

### Expected behaviour
The single deleted event should be gone.

### Actual behaviour
It's not gone, it's "cancelled". And it can't be deleted. Even if I delete the recurrence, the single "cancelled" event remains in place. It can be edited, for example set to "confirmed" and the UI is updated accordingly. But whenever I try to delete it, nothing happens. Only after reloading the web page, it's really gone. Maybe I was editing a ghost event all that time? I'm not sure, the events display is not reliable.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** PostgreSQL 10

**PHP version:** 7.0

**Server version:** 13

**Calendar version:** n/a (current as of this week)

**Updated from an older installed version or fresh install:** Initially a fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):** ?

### Client configuration
**Browser:** Firefox 59

**Operating system:** Windows 10

**CalDAV-clients:** DAVDroid

**Comment by rfc2822** [comment]
For the DAVdroid side: If you delete an event on Android devices, most calendar apps just mark them as cancelled, which will then be syncronized to Nextcloud. See https://forums.bitfire.at/topic/1238/synching-and-deleting-single-events-from-recurrent-repeating-events

**Comment by DrMartinus** [comment]
I just tried to cancel an event from a series of a recurring event, but that doesn't work - either the whole series is being cancelled, or nothing. There is a great need to improve the recurring events functionality. As it is, it can't be used really, and that's bad. **Any** other calendar app can do that better than nextcloud.  I found this thread [https://help.nextcloud.com/t/complex-repeat-rules/6111/2](url) and was surprised to see that the issue exists more than a year. I'm willing to help, because I think this is such an important feature, that I want it implemented fast. But I'm not sure how to go about it.

**Comment by georgehrke** [comment]
@DrMartinus We are working on making single events of a series editable. see #454

**Comment by georgehrke** [comment]
There was a bug in the handling of editing recurring exceptions. Will be fixed with #454.

**Comment by georgehrke** [comment]
As described above, the fact that an event is displayed as `CANCELLED` is done on purpose by Android.
Better handling of recurring events is part of  #7
