### ISSUE TITLE
Feature request - Delete all events of a calandar

### ISSUE THREAD

**Issue by Falseee** [nextcloud/calendar#804]
Hello, is it possible to implement a function to delete all events of a selected(maybe per right click) calendar.
An other option is to implement a better selection of events to delete.

**Comment by n0whereRuoxi** [comment]
could you just delete the hold layer

**Comment by Falseee** [comment]
@n0whereRuoxi 
That is no solution, because the calendar is shared with multiple peoples.
I just want to delete all events, so i can import new one and any body get the new events.

**Comment by n0whereRuoxi** [comment]
@Falseee it is a rare use case tho

**Comment by georgehrke** [comment]
As @n0whereRuoxi pointed out: This is a very rare use case.
If you repeatedly import events into the same calendar and delete the old events, you should use the Subscription feature instead of ordinary calendars.
We are also working on making subscriptions shareable: https://github.com/nextcloud/server/issues/1600

**Comment by s-hell** [comment]
I have the same Problem.

Subscriptions are cool but they are not always the solution.
In my example i need to import an ics (export from an internal business calendar).
This calendar can't be accessed over the internet. So i have to work with imports.

**Comment by Sanic** [comment]
Me too, for the same reasons that s-hell mentioned.

**Comment by EikeFeldmeier** [comment]
Me, too
