### ISSUE TITLE
[Feature Request] Share/Publish Calendars configurable as one calendar

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/calendar#806]
I use Nextcloud to manage some Familiemembers and their calendar. The crowd of Calendars grow more and more. We also got some Problems with Busines data which should not been shared with third persons.
The Davdroid accounts on smart-phone and thunder-bird is growing and growing. Now there is the big question to not include all away Dates because of Data security and privacy or to find a way to include only the interesting Data like the availability. Also we got some Problems with Calendar colours. It's got more and more chaotic to identify your own calendar/category entries among the others.

![grafik](https://user-images.githubusercontent.com/7795891/39136396-6e390ee4-471b-11e8-8b5a-3bc09351d0fe.png)

**Comment by Mannshoch** [comment]
@georgehrke It seems this is similar yes. the but my Idea seems a bit more enhanced than #708 I got a bit Inspired by #39 

@tcitworld Im not able to say that.

**Comment by Falseee** [comment]
+1 for multiple calendars as one link

**Comment by Mannshoch** [comment]
#725 and #39 seems the same in my opinion. #708 contains the concept of one dynamic calendar. My idea connects them into a whole concept. I tried to analyze the situation and problem I have and did a sketch for a concept which allow to solve my problem. I hope it's useful for you.

**Comment by georgehrke** [comment]
Ok, in that case I will close this issue and link your mockup in #708

**Comment by arnowelzel** [comment]
@Mannshoch I understand your motivation - but there are several issues with this feature:

1. Ho do you distinguish between the calendars when all events get merged in one single shared custom calendar?

2. If the shared calendar is writeable - what components should be allowed to be written? For example if you share only the event dates and titles of "Business" and "Business" is also writeable. Should event descriptions be ignored when writing them? Because when they are not shared to read, it would not make sense to allow writing them.

**Comment by Mannshoch** [comment]
1. I don't see an importance that the receiver of this share being able to distinguish between the calendars I use.
If needed maybe the Address book name could be reflected by a Category name. (see nextcloud/server#9422)
1. In my opinion, custom calendars would of course only be readable. In a future milestone maybe you could redirect the add of an event to an other calendar and ignore changes or if someone add a Text to Description/Title It could maybe added to the exist description.
  _
  If you allow me to propagate a somewhat crazy idea, I would write it into a tag <USERNAME> </USERNAME> in the description. The tag could then under certain circumstances not only include the changes but also mark areas that are readable by the recipient despite restrictions.
However, I do not believe that this will be implemented. :-)

**Comment by arnowelzel** [comment]
I don't see, why one should not see in which calendar an event is. For me it makes a big difference, if there is a business meeting with my collegues or if the meeting is just private with my family members. I see the calendar as a kind of category or property of the event.

For example, let's assume 3 calenders:

Private calendar of "Mannshoch"
Family calender of your family
Business calender of your company

Now you have an event "Lunch with Peter" in the  Business calendar and one of your family members is also named "Peter". Since there is no additional information, Peter might have to ask you, why you scheduled a lunch with him. Then you have to explain that this event is in the Business calendar and therefore he can just ignore that.

Maybe you should explain some use cases for this feature.

**Comment by Mannshoch** [comment]
Interessting point. In that case I would strongly prefer to include the calendar name in the Category of the calendar.
Otherwise, I wouldn't put all the calendars together into one like in Mockup. In many cases I would merge some business calendars, in other cases I would only take one and create a slim version of it. That would depend of the receiver of the calendar.
