### ISSUE TITLE
Display events in their local timezone

### ISSUE THREAD

**Issue by dotancohen** [nextcloud/calendar#819]
### Steps to reproduce
1. Add an event that is occurring in a location that you will be in at a later date, which is in a different time zone than you are in currently.
2. Expect to see that event listed in it's local timezone.
3. See the time translated to your current timezone.

### Expected behaviour
I expect to see events in the hour in which they will occur _locally for the event_.

### Actual behaviour
Event times are translated to the user's current timezone

Note that Fastmail has this option, they call it "floating time". See this HN thread for more details:
https://news.ycombinator.com/item?id=14010130

**Comment by georgehrke** [comment]
> ### Expected behaviour
> I expect to see events in the hour in which they will occur _locally for the event_.
> ### Actual behaviour
> Event times are translated to the user's current timezone

This is the absolutely expected behavior. If I'm invited to a conference call at 12pm eastern time, I obviously want to see it in Berlin time for myself and not 12pm.

If you edit the event, you will see the original time. 

You can also select a different timezone in the settings area in the lower left corner to see your calendar from a different timezone.

> Note that Fastmail has this option, they call it "floating time".

We support that feature. It's at the bottom of the timezone list and called none.
