### ISSUE TITLE
Touch input is not recognized

### ISSUE THREAD

**Issue by memen45** [nextcloud/calendar#851]
### Steps to reproduce
1. open calendar app
2. tap on the calendar to create a new item

### Expected behaviour
A new calendar item should be shown along with a pop-up element to enter details of the item

### Actual behaviour
Nothing

**Operating system**:
Ubuntu 16.04 LTS Server

**Web server:**
Apache2

**Database:**
MySQL

**Server version:**:
13.0.2

**Calendar version:**
1.6.1

**Updated from an older installed version or fresh install:**
Updated from 12 onwards, but not sure if this is introduced behaviour or always present

### Client configuration
**Browser:**
Firefox Quantum 60.0.2

**Operating system:**
Windows 10 (updated including april)
Android 6.0

**Comment by jaller94** [comment]
Thanks for bringing this up.
This is an issue for me as well.
Firefox 62 on Android 7

**Comment by memen45** [comment]
Just tested on another device, problem still present.

Firefox 63.0.2
Nextcloud 14.0.3
Calendar 1.6.4 (can't view the version in the app overview actually, but I updated last week or so, so I think should be 1.6.4)
Android 9.0.6

**Comment by georgehrke** [comment]
By migrating to our Nextcloud-vue framework for most of the UI, all non-calendar-grid items should properly respond to touch input now.

Everything calendar-grid related is mostly upstream related: https://github.com/fullcalendar/fullcalendar/issues?q=is%3Aissue+is%3Aopen+Touch+label%3ATouch

There are big improvements in Calendar 2 already, because we migrated to FullCalendar 4.0

Keeping this issue open for reference.

**Comment by szaimen** [comment]
It works on mobile. You simply need to press longer (around 2s or so).
