### ISSUE TITLE
Don't allowing to let events overlap

### ISSUE THREAD

**Issue by monsieurhannes** [nextcloud/calendar#893]
Hej,

I'm created several shared nextcloud calendars to book rooms and cars in our office. As there is no scheduling app yet and we kind of liked the style of nextcloud. However, when we select calendar "room a" for example from 9-12 AM someone else can still book it at the same time. Is it possible to disable the overlapping of two events in the same calendar? Or show a warning? That would be a good workaround for the scheduling/room booking that we need.

Thanks for your help! Great calendar!

**Comment by georgehrke** [comment]
> I'm created several shared nextcloud calendars to book rooms and cars in our office. As there is no scheduling app yet and we kind of liked the style of Nextcloud.

We are already working on implementing resource booking. Implementation in server is done: https://github.com/nextcloud/server/pull/9773 - just needs GUI.

>  Is it possible to disable the overlapping of two events in the same calendar? 

I don't want to disallow that, because that would clash with the CalDAV standard and could potentially result in unexpected behavior of other CalDAV clients.

>  Or show a warning? 

That warning would then again only be shown in the Calendar app, not on any CalDAV client on your mobile or desktop.

**Comment by georgehrke** [comment]
> That would be a good workaround for the scheduling/room booking that we need.

Given, that we are already working on implement resource booking, would you mind if i just close this ticket. There is no real need for a workaround, since we are working on the actual solution.

**Comment by monsieurhannes** [comment]
I wasn't aware that there is something in the pipe. Thank you for the update :) And for your work!
