### ISSUE TITLE
Unable to scroll the sidebar when having a lot of calendars

### ISSUE THREAD

**Issue by IwishIcanFLighT** [nextcloud/calendar#916]
### Steps to reproduce
1. Have a lot of calendar and/or subscriptions to calendars -around 14 for me, don't ask why-.
2. Add a 15th calendar
3. Voilà

![untitled-1](https://user-images.githubusercontent.com/4090502/46412583-40361580-c71f-11e8-985f-10f96717e28f.png)

### Expected behaviour
A scroll bar should appear in order to scroll through the list of calendars.

### Actual behaviour

The 15th calendar will barely show up a the bottom of the list. Making it impossible to edit (and same goes for any other added calendar. 
1080p screen using Firefox with zoom at 100%. A current workaround is to zoom at 90% or less.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/issue_template.md) as described in our [contributing guidelines](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md)

You didn't tell us what version etc ...

**Comment by jaller94** [comment]
I cannot reproduce this issue in Netxcloud 14.0.3 with Calendar 1.6.3 with Firefox Nightly 64.

I created calendars until a scroll bar appeared and then added 7 more subscriptions (because the screenshot shows mainly subscriptions). There were no issues. All calendars were fully visible when scrolling to the lower end of the list.
Even when resizing the browser window, the calendars showed up fine in the sidebar.

**Comment by IwishIcanFLighT** [comment]
I can confirm this is fixed for me as of 14.0.3 as well. Thanks!

**Comment by IwishIcanFLighT** [comment]
I can confirm this is fixed for me as of 14.0.3 as well. Thanks!

**Comment by IwishIcanFLighT** [comment]
I can confirm this is fixed as of 14.0.3. Thanks!
