### ISSUE TITLE
Integrity check fails (signature.json does not exist)

### ISSUE THREAD

**Issue by albinou** [nextcloud/calendar#948]
### Steps to reproduce
1. Run `sudo -u www-data php occ integrity:check-app calendar`

### Expected behaviour
The command should return without errors.

### Actual behaviour
On my server, it returns the following:

```
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.
```

I also noticed that the file `calendar/appinfo/signature.json` does NOT exist. Is it normal?

### Server configuration

**Operating system**: Debian Linux 9.6

**Web server:** nginx/1.15.6

**Database:** mariadb

**PHP version:** 7.0.30

**Server version:** 14.0.3

**Calendar version:** 1.6.3

**Updated from an older installed version or fresh install:** Updated from Nextcloud 12

**Signing status (ownCloud/Nextcloud 9.0 and above):**

I am using an `extra-apps` folder configured with `apps_path` in the `config.php` file:

```
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/srv/cloud.example.org/www/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/srv/cloud.example.org/www/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
```

And I currently meet the issue mentioned [here](https://github.com/nextcloud/server/issues/12541#issue-382416586).

**Comment by georgehrke** [comment]
> I also noticed that the file calendar/appinfo/signature.json does NOT exist. Is it normal?

We don't ship a signature.json anymore for ages. We sign the calendar.tar.gz we upload to the App Store. See https://apps.nextcloud.com/apps/calendar/releases?platform=14#14

I can't see any mistake in the calendar app and strongly suspect this to be an issue in the Nextcloud server's `php occ integrity:check-app` command, as you also seem to have a general issue with `php occ integrity` regarding app-folders. Closing, since there already is a ticket in the server that you linked
